### Use Case : Use Generative AI to perform success comparison of multiple actors/actresses
#### Suggesting production house/producers which actor/actress will be suitable for next project out of pool of actors.
#### Dimensions -


- No. of Awards won
- Media and Magazines review
- Audience Popularity & Rating Summary
- Media polls and opinions
- Twitter audience review
- Weighted average
- Movie Success
- Box Office Success
- Same character portrayal
- Box office success
- Social media presence and followers
- Success factors
- Actors performance analysis
- Good acting vs bad acting
- Actors performance accuracy
- Magnitude of actors Star Power to influence success of a movie

In [91]:
#!pip install langchain

In [92]:
import pandas as pd
import numpy as np
import ast
#from sklearn.feature_extraction.text import CountVectorizer
#from sklearn.metrics.pairwise import cosine_similarity
import pickle
import warnings
import requests

# import libraries
import openai
import os
from langchain.llms import OpenAI
from langchain.agents import load_tools
from langchain.agents import initialize_agent
#from dotenv import load_dotenv
#load_dotenv()

In [93]:
# load API keys; you will need to obtain these if you haven't yet
os.environ["OPENAI_API_KEY"] = "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"
os.environ["SERPAPI_API_KEY"] = "c7301c956f8df074e0b1ee763cdd248cc67164f5a0e18a68fb3ec3bb57a33c49"

apikey = "c44ca52d"
openai.api_key = "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"

In [94]:
movies = pd.read_pickle('models/movies.pkl')
movies_data = pd.read_pickle('models/movies_data.pkl')

In [95]:
movies.head(2)

,id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[cultureclash, future, spacewar, spacecolony, ..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[ocean, drugabuse, exoticisland, eastindiatrad..."

In [96]:
movies_data.head(2)

,id,production_countries,cast,crew,release_date,genres,runtime,tagline,vote_average,vote_count
0,19995,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'Director': 'James Cameron'}, {'Screenplay':...",2009-12-10,"[Action, Adventure, Fantasy, Science Fiction]",162.0,Enter the World of Pandora.,7.2,11800
1,285,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{'cast_id': 4, 'character': 'Captain Jack Spa...","[{'Director': 'Gore Verbinski'}, {'Screenplay'...",2007-05-19,"[Adventure, Fantasy, Action]",169.0,"At the end of the world, the adventure begins.",6.9,4500

In [97]:
# # Define the actor's name and genres
# actor_name = 'Actor Name'
# genres = ['genre1', 'genre2', 'genre3']  # Specify the genres you want to analyze

# # Define the prompt
# prompt = f"Analyzing {actor_name}'s success in different genres:\n"

In [98]:
# # Generate the completion using the GPT-3.5 Turbo model
# response = openai.Completion.create(
#     engine='text-davinci-003',  # Specify the GPT model
#     prompt=prompt,
#     max_tokens=100,  # Adjust the desired length of the response
#     n=1,  # Number of completions to generate
#     stop=None,  # Optional stop sequence to limit the response
# )

# # Extract the generated completion from the API response
# result = response.choices[0].text.strip()

# # Print the generated completion
# print(result)

### Using GPT 4.0

In [99]:
import requests
import json

In [100]:
import requests
import json

API_KEY = os.environ["OPENAI_API_KEY"]
API_ENDPOINT = "https://api.openai.com/v1/chat/completions"

def generate_chat_completion(messages, model="gpt-4-0613", temperature=0, max_tokens=None):
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {API_KEY}",
    }

    data = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
    }

    if max_tokens is not None:
        data["max_tokens"] = max_tokens

    response = requests.post(API_ENDPOINT, headers=headers, data=json.dumps(data))

    if response.status_code == 200:
        return response.json()["choices"][0]["message"]["content"]
    else:
        raise Exception(f"Error {response.status_code}: {response.text}")

### Use Case : Autogenerate keywords on various aspects like Mood, Theme, Settings, etc. for series

In [102]:
prompt = f"""Please autogenerate keywords for a particular series 'Ancient Aliens' on various aspects like Mood, Theme, \
        Settings, Characters, Plot Elements, Symbolism, Relationships, Style, Tone, Diversity (generate keywords from the series\
        which involves all the ways how people are different, including the various characteristics that distinguish one \
        demographic or individual from another), Equity (generate keywords from the series which ensure equal treatment, access, \
        opportunity and advancement for people, identify and remove barriers), Inclusion(generate keywords from the series that \
        builds a culture that invites every person and group to contribute and participate in an inclusive, welcoming environment \
        supports and embraces differences), Production, Recognition \
        - Take some time and think deep before coming up with the keywords and generate keywords as unique as possible \
        - I donot want any solution step in the output but just the above list of 14 aspects and nothing else
        - There should be 10 keywords generated for each aspect \
        - Print output of each aspect in a comma separated python list format. """

messages = [
    {"role": "system", "content": "You are an AI assistant from media domain with enormous knowledge on movie and series insights."},
    {"role": "user", "content": prompt}
]

In [103]:
response_text = generate_chat_completion(messages)
print(response_text)

Mood: ['Intriguing', 'Mysterious', 'Thought-provoking', 'Suspenseful', 'Educational', 'Fascinating', 'Unsettling', 'Curious', 'Enlightening', 'Speculative']

Theme: ['Extraterrestrial Life', 'Ancient Civilizations', 'Unexplained Phenomena', 'Conspiracy Theories', 'Historical Mysteries', 'Scientific Speculation', 'Ancient Technology', 'Alien Influence', 'Mythology', 'Archaeological Discoveries']

Settings: ['Ancient Egypt', 'Mayan Civilization', 'Stonehenge', 'Pyramids', 'Ancient Rome', 'Machu Picchu', 'Atlantis', 'Ancient Greece', 'Nazca Lines', 'Great Wall of China']

Characters: ['Historians', 'Scientists', 'Archaeologists', 'Theorists', 'Narrator', 'Ancient Civilizations', 'Aliens', 'Researchers', 'Experts', 'Ancient Gods']

Plot Elements: ['Alien Encounters', 'Ancient Artifacts', 'Historical Analysis', 'Scientific Theories', 'Archaeological Excavations', 'Mythological Stories', 'Unexplained Events', 'Ancient Texts', 'Alien Technology', 'Conspiracy Theories']

Symbolism: ['Pyramids', 'Hieroglyphs', 'Ancient Artifacts', 'Crop Circles', 'Alien Symbols', 'Ancient Monuments', 'Sacred Geometry', 'Ancient Scripts', 'Mysterious Structures', 'Unidentified Flying Objects']

Relationships: ['Historians and Theorists', 'Past and Present', 'Science and Mythology', 'Humans and Aliens', 'Facts and Speculations', 'Ancient and Modern Technology', 'Earth and Outer Space', 'Reality and Conjecture', 'Evidence and Interpretation', 'History and Future']

Style: ['Documentary', 'Investigative', 'Expository', 'Narrative', 'Analytical', 'Speculative', 'Educational', 'Historical', 'Scientific', 'Theoretical']

Tone: ['Serious', 'Inquisitive', 'Analytical', 'Speculative', 'Objective', 'Educational', 'Mysterious', 'Controversial', 'Informative', 'Provocative']

Diversity: ['Global Perspectives', 'Cultural Diversity', 'Historical Diversity', 'Scientific Opinions', 'Theoretical Diversity', 'Diverse Civilizations', 'Diverse Interpretations', 'Multicultural Experts', 'Diverse Beliefs', 'Diverse Mythologies']

Equity: ['Equal Representation of Theories', 'Balanced Perspectives', 'Equal Voice to Experts', 'Fair Analysis', 'Equal Access to Information', 'Unbiased Narration', 'Equal Consideration of Opinions', 'Fair Representation of Cultures', 'Equal Emphasis on Evidence', 'Balanced Interpretation']

Inclusion: ['Inclusive of All Theories', 'Respect for All Cultures', 'Inclusive Narration', 'Acceptance of Diverse Opinions', 'Inclusion of Diverse Civilizations', 'Inclusive of All Evidence', 'Inclusion of Diverse Beliefs', 'Inclusive of All Historical Periods', 'Inclusive of All Scientific Fields', 'Inclusive of All Mythologies']

Production: ['High Quality Visuals', 'Detailed Research', 'Expert Interviews', 'Historical Reenactments', 'Archival Footage', 'Professional Narration', 'Scientific Analysis', 'On-location Filming', 'In-depth Investigation', 'Comprehensive Documentation']

Recognition: ['Popular Among Conspiracy Theorists', 'Highly Rated', 'Cult Following', 'Acclaimed by History Buffs', 'Recognized by Scientists', 'Popular in Pop Culture', 'Widely Discussed', 'Internationally Known', 'Frequently Referenced', 'Highly Viewed']

In [62]:
type(response_text)

str

In [78]:
# Extracting categories from the input string
MoodList = ['Mood:']
if any(x in response_text for x in MoodList):
    MoodList_start_index = response_text.find("Mood:") + len("Mood:")
    MoodList_end_index = response_text.find("Theme:")
    
MoodList_string = response_text[MoodList_start_index:MoodList_end_index]

print("Mood:", MoodList_string)

Mood:  ['Mysterious', 'Intriguing', 'Thought-provoking', 'Enigmatic', 'Suspenseful', 'Fascinating', 'Curious', 'Puzzling', 'Unsettling', 'Captivating']

In [79]:
print(MoodList_string)

 ['Mysterious', 'Intriguing', 'Thought-provoking', 'Enigmatic', 'Suspenseful', 'Fascinating', 'Curious', 'Puzzling', 'Unsettling', 'Captivating']

In [87]:
input_string = MoodList_string
# Removing unwanted characters
cleaned_string = input_string.replace("[", "").replace("]", "").replace("'", "")

print(cleaned_string)

 Mysterious, Intriguing, Thought-provoking, Enigmatic, Suspenseful, Fascinating, Curious, Puzzling, Unsettling, Captivating

In [85]:
MoodList_string

" 'Mysterious', 'Intriguing', 'Thought-provoking', 'Enigmatic', 'Suspenseful', 'Fascinating', 'Curious', 'Puzzling', 'Unsettling', 'Captivating'\n\n"

In [88]:
emotions_list = cleaned_string.split(",")
emotions = [emotion.strip() for emotion in emotions_list if emotion.strip()]

In [89]:
emotions

['Mysterious',
 'Intriguing',
 'Thought-provoking',
 'Enigmatic',
 'Suspenseful',
 'Fascinating',
 'Curious',
 'Puzzling',
 'Unsettling',
 'Captivating']

In [90]:
for emo in emotions:
    print(emo)

Mysterious
Intriguing
Thought-provoking
Enigmatic
Suspenseful
Fascinating
Curious
Puzzling
Unsettling
Captivating

In [41]:
# Extracting categories from the input string
ThemeList = ['Theme:']
if any(x in response_text for x in ThemeList):
    ThemeList_start_index = response_text.find("Theme:") + len("Theme:")
    ThemeList_end_index = response_text.find("Settings:")
    
ThemeList_string = response_text[ThemeList_start_index:ThemeList_end_index]

print("Theme:", ThemeList_string)

Theme:  ['Extraterrestrial Life', 'Ancient Civilizations', 'Unexplained Phenomena', 'Conspiracy Theories', 'Historical Mysteries', 'Advanced Technologies', 'Ancient Knowledge', 'Alien Influence', 'Interstellar Travel', 'Ancient Astronaut Theory']

In [42]:
# Extracting categories from the input string
SettingsList = ['Settings:']
if any(x in response_text for x in SettingsList):
    SettingsList_start_index = response_text.find("Settings:") + len("Settings:")
    SettingsList_end_index = response_text.find("Characters:")
    
SettingsList_string = response_text[SettingsList_start_index:SettingsList_end_index]

print("Settings:", SettingsList_string)

Settings:  ['Ancient Egypt', 'Mayan Ruins', 'Stonehenge', 'Pyramids', 'Underwater Cities', 'Cave Paintings', 'Ancient Temples', 'Space', 'Historical Landmarks', 'Alien Planets']

In [43]:
# Extracting categories from the input string
CharactersList = ['Characters:']
if any(x in response_text for x in CharactersList):
    CharactersList_start_index = response_text.find("Characters:") + len("Characters:")
    CharactersList_end_index = response_text.find("Plot Elements:")
    
CharactersList_string = response_text[CharactersList_start_index:CharactersList_end_index]

print("Characters:", CharactersList_string)

Characters:  ['Historians', 'Scientists', 'Archaeologists', 'Astronomers', 'Theorists', 'Researchers', 'Narrator', 'Experts', 'Ancient Civilizations', 'Aliens']

In [45]:
# Extracting categories from the input string
PlotElementsList = ['Plot Elements:']
if any(x in response_text for x in PlotElementsList):
    PlotElementsList_start_index = response_text.find("Plot Elements:") + len("Plot Elements:")
    PlotElementsList_end_index = response_text.find("Symbolism:")
    
PlotElementsList_string = response_text[PlotElementsList_start_index:PlotElementsList_end_index]

print("Plot Elements:", PlotElementsList_string)

Plot Elements:  ['Alien Encounters', 'Ancient Artifacts', 'Unexplained Structures', 'Historical Evidence', 'Scientific Analysis', 'Theoretical Discussions', 'Ancient Texts', 'Alien Technology', 'Archaeological Discoveries', 'Space Exploration']

In [46]:
# Extracting categories from the input string
SymbolismList = ['Symbolism:']
if any(x in response_text for x in SymbolismList):
    SymbolismList_start_index = response_text.find("Symbolism:") + len("Symbolism:")
    SymbolismList_end_index = response_text.find("Relationships:")
    
SymbolismList_string = response_text[SymbolismList_start_index:SymbolismList_end_index]

print("Symbolism:", SymbolismList_string)

Symbolism:  ['Pyramids', 'Hieroglyphs', 'Crop Circles', 'Ancient Artifacts', 'Alien Symbols', 'Sacred Geometry', 'Ancient Monuments', 'Astronomical Alignments', 'Mysterious Structures', 'Unidentified Flying Objects']

In [47]:
# Extracting categories from the input string
RelationshipsList = ['Relationships:']
if any(x in response_text for x in RelationshipsList):
    RelationshipsList_start_index = response_text.find("Relationships:") + len("Relationships:")
    RelationshipsList_end_index = response_text.find("Style:")
    
RelationshipsList_string = response_text[RelationshipsList_start_index:RelationshipsList_end_index]

print("Relationships:", RelationshipsList_string)

Relationships:  ['Historians and Theorists', 'Past and Present', 'Science and Mythology', 'Humans and Aliens', 'Facts and Speculations', 'Evidence and Interpretation', 'Ancient and Modern Technology', 'Earth and Cosmos', 'Reality and Conspiracy', 'Knowledge and Belief']

In [48]:
# Extracting categories from the input string
StyleList = ['Style:']
if any(x in response_text for x in StyleList):
    StyleList_start_index = response_text.find("Style:") + len("Style:")
    StyleList_end_index = response_text.find("Tone:")
    
StyleList_string = response_text[StyleList_start_index:StyleList_end_index]

print("Style:", StyleList_string)

Style:  ['Documentary', 'Investigative', 'Expository', 'Narrative', 'Analytical', 'Speculative', 'Educational', 'Historical', 'Scientific', 'Theoretical']

In [49]:
# Extracting categories from the input string
ToneList = ['Tone:']
if any(x in response_text for x in ToneList):
    ToneList_start_index = response_text.find("Tone:") + len("Tone:")
    ToneList_end_index = response_text.find("Diversity:")
    
ToneList_string = response_text[ToneList_start_index:ToneList_end_index]

print("Tone:", ToneList_string)

Tone:  ['Serious', 'Inquisitive', 'Analytical', 'Speculative', 'Objective', 'Informative', 'Controversial', 'Debative', 'Educational', 'Provocative']

In [50]:
# Extracting categories from the input string
DiversityList = ['Diversity:']
if any(x in response_text for x in DiversityList):
    DiversityList_start_index = response_text.find("Diversity:") + len("Diversity:")
    DiversityList_end_index = response_text.find("Equity:")
    
DiversityList_string = response_text[DiversityList_start_index:DiversityList_end_index]

print("Diversity:", DiversityList_string)

Diversity:  ['Global Perspectives', 'Cultural Diversity', 'Historical Diversity', 'Scientific Opinions', 'Theoretical Diversity', 'Diverse Civilizations', 'Diverse Expertise', 'Diverse Interpretations', 'Diverse Locations', 'Diverse Time Periods']

In [51]:
# Extracting categories from the input string
EquityList = ['Equity:']
if any(x in response_text for x in EquityList):
    EquityList_start_index = response_text.find("Equity:") + len("Equity:")
    EquityList_end_index = response_text.find("Inclusion:")
    
EquityList_string = response_text[EquityList_start_index:EquityList_end_index]

print("Equity:", EquityList_string)

Equity:  ['Balanced Perspectives', 'Equal Representation of Theories', 'Fair Analysis', 'Unbiased Narration', 'Equal Voice to Experts', 'Impartial Investigation', 'Equal Consideration of Evidence', 'Fair Representation of Cultures', 'Equitable Exploration', 'Balanced Interpretation']

In [52]:
# Extracting categories from the input string
InclusionList = ['Inclusion:']
if any(x in response_text for x in InclusionList):
    InclusionList_start_index = response_text.find("Inclusion:") + len("Inclusion:")
    InclusionList_end_index = response_text.find("Production:")
    
InclusionList_string = response_text[InclusionList_start_index:InclusionList_end_index]

print("Inclusion:", InclusionList_string)

Inclusion:  ['Inclusive of All Theories', 'Inclusive of All Evidence', 'Inclusive of Diverse Cultures', 'Inclusive of Various Disciplines', 'Inclusive of Different Opinions', 'Inclusive of All Historical Periods', 'Inclusive of Global Locations', 'Inclusive of All Civilizations', 'Inclusive of Scientific and Mythological Aspects', 'Inclusive of Ancient and Modern Perspectives']

In [54]:
# Extracting categories from the input string
ProductionList = ['Production:']
if any(x in response_text for x in ProductionList):
    ProductionList_start_index = response_text.find("Production:") + len("Production:")
    ProductionList_end_index = response_text.find("Recognition:")
    
ProductionList_string = response_text[ProductionList_start_index:ProductionList_end_index]

print("Production:", ProductionList_string)

Production:  ['High-quality Visuals', 'Detailed Research', 'Expert Interviews', 'Historical Reenactments', 'Archival Footage', 'Computer-generated Imagery', 'On-location Filming', 'Narrative Voice-over', 'Thorough Investigation', 'Professional Editing']

In [53]:
# Extracting categories from the input string
RecognitionList = ['Recognition:']
if any(x in response_text for x in RecognitionList):
    RecognitionList_start_index = response_text.find("Recognition:") + len("Recognition:")
    
RecognitionList_string = response_text[RecognitionList_start_index:]

print("Recognition:", RecognitionList_string)

Recognition:  ['Popular Among Conspiracy Theorists', 'Cult Following', 'Highly Debated', 'Critically Discussed', 'Widely Recognized', 'Popular in Pop Culture', 'Referenced in Other Media', 'Long-running Series', 'Internationally Broadcasted', 'Recognized for Provoking Thought']

In [57]:
warnings.filterwarnings("ignore")
aetn_series = pd.read_csv('Series.csv')

In [61]:
aetn_series['SERIES'].astype(str).unique()

array(['60 Days In', '60 Days In: Narcoland',
       'Accused: Guilty or Innocent?', 'Alone', 'Alone: The Beast',
       'America: Our Defining Hours', 'American Pickers',
       'American Ripper', "America's Book of Secrets",
       "America's Book of Secrets: Special Edition", 'Ancient Aliens',
       'Ancient Top 10', 'Barbarians Rising', 'Behind Bars: Rookie Year',
       'Beyond Oak Island', 'Beyond Scared Straight',
       'Beyond the Headlines: Escaping the NXIVM Cult with Gretchen Carlson',
       'Beyond the Headlines: The College Admissions Scandal With Gretchen Carlson',
       'Biography: The Trump Dynasty', 'Born Behind Bars',
       'Born This Way', 'Bride and Prejudice: Forbidden Love',
       'Bring It!', 'Celebrity Ghost Stories (2009)',
       'Cheerleader Generation', 'Chris Farley: Anything for a Laugh',
       'Cities of the Underworld', 'Cold Case Files', 'Crazy Love',
       'Crime 360', 'Cults and Extreme Belief', 'Cultureshock',
       'Dance Moms', 'Dating App Horrors: The Untold Story', 'Dead Again',
       'Deadly Wives', 'Desafio Sobre Fuego', 'Detroit: Comeback City',
       'Divided States', 'Duck Dynasty', 'Escaping Polygamy',
       'Estados Unidos: Horas Decisivas De Su Historia', 'Forged in Fire',
       'Forged in Fire: Beat the Judges',
       'Forged in Fire: Knife or Death', 'Found', 'Gangland Undercover',
       'Ghost Hunters', 'Glam Masters', 'Going Si-Ral',
       'Gold Medal Families', 'Grace vs. Abrams',
       'Hangar 1: The UFO Files', 'Hoarders', 'Hunting Hitler',
       "Hunting JonBenét's Killer: The Untold Story",
       'I Survived...Beyond and Back',
       'I Was a Child Bride: The Untold Story', 'Intervention',
       'JFK Declassified: Tracking Oswald',
       'Kids Behind Bars: Life or Parole', 'Kingpin', 'Kings of Pain',
       'Leah Remini: Scientology and the Aftermath',
       'Little Women: Atlanta', 'Little Women: Dallas',
       'Little Women: LA', 'Lost Gold of World War II',
       'Making a Model With Yolanda Hadid', 'Man vs. Master: Chef Battle',
       'Many Sides of Jane', 'Married at First Sight',
       'Married at First Sight: Jamie and Doug Plus One',
       'Married at First Sight: Unmatchables', 'Marrying Millions',
       'Mary Kills People', 'Meghan and Harry: Baby Fever',
       'Monster In-Laws', 'Mountain Men',
       'My Great Big Live Wedding With David Tutera', 'My Sordid Affair',
       'Nightwatch', 'Nightwatch Nation', 'Nostradamus Effect',
       'Obsessed', 'Panic 9-1-1', 'Pawn Stars', 'Project Runway',
       'Project Runway All Stars', 'Psychic Kids', "Raising Tourette's",
       'Roots', 'Secret Life of a Gang Girl: The Untold Story',
       'Seven Year Switch', 'Sex for Sale: The Untold Story', 'SIX',
       'Steven Seagal: Lawman', 'Storage Wars', 'Swamp People',
       'The American Farm', 'The Curse of Civil War Gold',
       'The Curse of Oak Island', 'The Day I Picked My Parents',
       'The First 48', 'The First 48 Presents: Homicide Squad Atlanta',
       'The Food That Built America', 'The Hunt for the Zodiac Killer',
       'The Killer Speaks', 'The Lowe Files',
       'The Menendez Murders: Erik Tells All',
       'The Murder of Laci Peterson', 'The Rap Game',
       'The Secret of Skinwalker Ranch',
       'The Selection: Special Operations Experiment',
       'The Strongest Man in History', 'The Tesla Files', 'The Toe Bro',
       'The Universe', 'The UnXplained', 'TRANsitioning',
       'UFOs: Secret Alien Technology', 'UFOs: Secret Missions Exposed',
       'Undercover High', 'Undercover High: After School', 'UnREAL',
       'War & Peace', 'Who Killed Tupac?'], dtype=object)

### Using gpt-3.5-turbo-16k  - For more contest 4 times

In [237]:
def generate_response(prompt, model="gpt-3.5-turbo-16k"):
    messages = [{"role": "user", "content": prompt}]
    response = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=0, # this is the degree of randomness of the model's output
    )
    return response.choices[0].message["content"]

In [238]:
prompt = f"""
            I want you to find out the below specific information - \
               1. What are the movies Tom Hanks did on Drama genre?  \
               2. Did he win any award for those above genre movies? \
               3. Did he get any nomination for those genre movies?
            """
response = generate_response(prompt)
response

'1. Tom Hanks has appeared in several drama genre movies. Some notable ones include:\n\n- Forrest Gump (1994)\n- Philadelphia (1993)\n- Saving Private Ryan (1998)\n- Cast Away (2000)\n- Captain Phillips (2013)\n- Bridge of Spies (2015)\n- The Post (2017)\n\n2. Yes, Tom Hanks has won awards for his performances in drama genre movies. He won the Academy Award for Best Actor for his roles in Philadelphia (1993) and Forrest Gump (1994).\n\n3. Tom Hanks has received numerous nominations for his performances in drama genre movies. Apart from winning the Academy Award, he has been nominated for several other prestigious awards such as the Golden Globe Awards, BAFTA Awards, and Screen Actors Guild Awards for his roles in various drama films.'

In [109]:
prompt = f"""
            I want you to find out the below specific information - \
               - Search for awards, reviews, feedbacks, opinions, polls on actor Bill Skarsgard and \
               put all under separate lists
               - Based on all information received above, calculate a weighted average on a scale of 1 to 100 \
               based on positive and negative contributions in all his work taken together
            """
response = generate_response(prompt)
response

'List of Awards:\n- 2018: MTV Movie Award for Best Villain for his role as Pennywise in "It"\n- 2018: Fright Meter Award for Best Supporting Actor for his role as Pennywise in "It"\n- 2018: Saturn Award for Best Supporting Actor for his role as Pennywise in "It"\n- 2019: Scream Award for Best Villain for his role as Pennywise in "It Chapter Two"\n\nList of Reviews/Feedbacks/Opinions:\n- "Skarsgard is a revelation as Pennywise, bringing a terrifying and unpredictable energy to the role." - Rotten Tomatoes\n- "Bill Skarsgard is a standout as Pennywise, delivering a performance that is both terrifying and captivating." - Screen Rant\n- "Skarsgard\'s performance as Pennywise is nothing short of iconic." - Collider\n- "Bill Skarsgard is a master of his craft, bringing a level of nuance and depth to his characters that is rare in horror films." - Bloody Disgusting\n\nList of Polls:\n- In a poll conducted by Ranker, Bill Skarsgard was voted the 4th best horror movie actor of all time.\n- In a poll conducted by PopSugar, Bill Skarsgard was voted the scariest movie villain of all time for his role as Pennywise in "It".\n\nWeighted Average:\nBased on the positive contributions from the awards, reviews, feedbacks, and polls, Bill Skarsgard\'s weighted average would be around 85 out of 100. However, without any negative contributions to balance out the positive, this calculation may not accurately reflect his overall impact as an actor.'

## Using LangChain

In [6]:
from langchain.output_parsers import ResponseSchema
from langchain.output_parsers import StructuredOutputParser
from langchain.prompts import ChatPromptTemplate
from langchain.chat_models import ChatOpenAI

In [7]:
chat = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0.0, verbose="True")
chat

ChatOpenAI(verbose=True, callbacks=None, callback_manager=None, client=<class 'openai.api_resources.chat_completion.ChatCompletion'>, model_name='gpt-3.5-turbo', temperature=0.0, model_kwargs={}, openai_api_key='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', openai_api_base='', openai_organization='', openai_proxy='', request_timeout=None, max_retries=6, streaming=False, n=1, max_tokens=None)

In [14]:
gpt_input = "Al Paccino, Robert Di Niro"

In [15]:
actor_performance_analysis = """What it takes for an actor to be successful in a genre?\
                \
                Below bunch of items refer to what the actor does to prepare (before the performance) for the role:\
                - Visibility of the Actor : Describe the physical characteristics of the actor: height, weight, body type, age, ethnicity, nationality, \
                speaking style (including native language and accent),etc \
                - Actor Transformation : Describe what the actor has done to change and/or mold his/her own physical, facial, vocal characteristics for \
                this performance \
                - Style of Acting : Describe the acting style if relevantand note the film genre and/or type of part in this film (comic, farcical, \
                serious, romantic, tragic, musical-note singing/dancing skills -historical, fantastical, etc.) \
                - Connections with other characters : Briefly describe the traits and function of the character portrayed in the film, as well as his or her \
                relationships with other characters.What does this actor do to make this character come alive? \
                - Popular Scene : Describe a key scene in which this actor plays an important role and tell what idea and feeling is \
                communicated by this scene.Tell what the character does, in general, to further the story in this scene."""
            

good_acting_vs_bad_acting = """Examples of Bad Acting:\
                - Overacting : A bad actor might perform in a way that’s overly exaggerated, leading to corny, over-the-top \
                performances, overacting. \
                Example: Tommy Wiseau as Johnny in "The Room" \
                - Unbelievable : If an actor can’t make the audience believe that they are truly inhabiting their character,\
                it can ruin the entire production\
                Example: Mark Wahlberg as Elliot Moore in "The Happening"\
                - Predictable : If the audience can predict your every move, they’re not going to be engaged in your \
                performance\
                Example: Dean Cain in any (shockingly large) number of Christmas movies \
                - Dull : A lack of confidence, energy, and excitement simply isn’t engaging to watch.\
                Example: Duke Moore as Lieutenant Harper in "Plan 9" From Outer Space'  \
                \
                Examples of Good Acting:\
                - Nuanced : Good acting feels realistic, which means it’s subtle and nuanced but still indicates complex \
                interior states \
                Example: Pam Grier as Jackie and Robert Forster as Max in "Jackie Brown" \
                - Believable : "An actor is good if he makes me believe he’s actually going through whatever his character is\
                going through" said director Marcus Geduld on Quora \
                Example: Viola Davis as Rose Maxson and Denzel Washington as Troy Maxson in "Fences" \
                - Surprising : Conversely, a good actor’s performance contains an element of surprise that intrigues and \
                delights viewers. \
                Example: Jack Nicholson as Jack Torrance in "The Shining" \
                - Charismatic : Alternatively, the ability to be present and exude enthusiasm and confidence takes a \
                performance to the next level. \
                Example: Jason Sudeikis as the titular Ted Lasso in 'Ted Lasso' """


actor_performance_accuracy = """How accurate the actor performance is in context according to: \
                - History \
                - Storyline \
                - Society \
                - Culture \
                - Source material \
                - Performance Depth  \
                  -- Emotional level \
                  -- Psychological level \
                - Character Portrayal \
                  -- Social \
                  -- Historical \
                  -- Cultural context \
                - Actor Talent - research and work put into performance \
                - Critical Recognition \
                - Performance Impact - remember and recall this performance long after seeing the film."""


weighted_average_calculation_prompt = """You have to calculate Weighted Average. Let's take an example of actor Hugh Jackman. \
To calculate the weighted average, we will assign a score of 1 to 100 to each piece of information based on its positive or \
negative contribution to Hugh Jackman's overall reputation. \
\
For example, an award win would receive a high positive score, while a negative review would receive a low negative score.\
We will then calculate the average of all scores to arrive at the final weighted average. \
                                      \
Here is an example calculation, but you work on it as per user input of actor/actress: \
- Academy Award nomination (+90)\
- Golden Globe win (+80)\
- Emmy win (+70)\
- Tony win (+90)\
- Positive Rotten Tomatoes review (+80)\
- Positive Broadway World review (+80)\
- Positive The Guardian review (+80)\
- Positive Variety review (+80)\
- Likable actor poll (+70)\
- Admired man survey (+60)\
- Wolverine actor poll (+80)\
\
Total score: 870 \
\
Weighted average: 79.09 (rounded to 79) \
\
Based on the information gathered, Hugh Jackman\'s overall reputation is positive, with a weighted average score of \
79 out of 100. \

Also out of Total Score, add or subtract accordingly as per below format
- Each positive Media Source Review (+5)\
- Each negative Media Source Review (-5)\
- Each positive Media Opinion and Poll Review (+5)\
- Each negative Media Opinion and Poll Review (-5)\
\
Do the weighted average and calculate weighted average score once again and give the final response back."""

## GPT Call #1

In [18]:
awards_list_schema = ResponseSchema(name="awards_list",
                             description="List of all the Awards won by the actors as per input criteria and in which movie/show/series and display in python List format \
                             Also,Compare the final results between the actors given as input, judge, calculate and assign points to the actors \
                            separately on those factors, display them separately for each actor in a separate python dictionary and lastly come up with a winner in the format -\
                            <Winner> : <Actor name> - <mention factors where the actor surpassed all other actors given in input> in list format")

media_reviews_list_schema = ResponseSchema(name="media_reviews_list",
                                      description="List of all top influencial Reviews and Feedbacks both postive and negative from famous magazines and media sources till now.\
                                      along with Audience rating summary for each actor separately in dictionary. Display output in a python Dictionary format - <movie name> : <review and feedback in raw text format for each>, <media source name in raw text> \
                                      : <extracted sentiment for each>. Also give the calculated Overall Sentiment from all reviews in the format \
                                      <'Overall Sentiment'> text as KEY and the extracted Overall Sentiment as VALUE \
                                      Also,Compare the final results between the actors given as input, judge, calculate and assign points to the actors \
                                    separately on those factors, display them separately for each actor in a separate python dictionary and lastly come up with a winner in the format -\
                                    <Winner> : <Actor name> - <mention factors where the actor surpassed all other actors given in input> in list format")

response_schemas_1 = [awards_list_schema, 
                    media_reviews_list_schema]

In [19]:
user_prompt_1 = """- Search for awards won and nominated both and put all under separate lists.\
                - Search for reviews and feedbacks from top influential media sources"""

output_parser_1 = StructuredOutputParser.from_response_schemas(response_schemas_1)

format_instructions_1 = output_parser_1.get_format_instructions()

review_template_1 = """\
        You are a movie analyst who has to analyze, think, understand all the information given below in the \
        instructed format, identify success factors for actors {gpt_input} based on these \
        information and come up with all the detailed points. Do not hallucinate, come up with only real information.\

        text: {text}

        {format_instructions}
"""

prompt_1 = ChatPromptTemplate.from_template(template=review_template_1)

messages = prompt_1.format_messages(text=user_prompt_1, 
                                format_instructions=format_instructions_1,gpt_input=gpt_input)

#print(messages[0].content)
response = chat(messages)
output_dict_1 = output_parser_1.parse(response.content)
output_dict_1

{'awards_list': {'Al Pacino': [{'award': 'Academy Award for Best Actor',
    'movie': 'Scent of a Woman',
    'result': 'Won'},
   {'award': 'Golden Globe Award for Best Actor – Motion Picture Drama',
    'movie': 'Scent of a Woman',
    'result': 'Won'},
   {'award': 'Primetime Emmy Award for Outstanding Lead Actor in a Miniseries or a Movie',
    'movie': 'Angels in America',
    'result': 'Won'},
   {'award': 'Golden Globe Award for Best Actor – Miniseries or Television Film',
    'movie': 'Angels in America',
    'result': 'Won'},
   {'award': 'Screen Actors Guild Award for Outstanding Performance by a Male Actor in a Leading Role',
    'movie': 'The Irishman',
    'result': 'Nominated'}],
  'Robert Di Niro': [{'award': 'Academy Award for Best Actor',
    'movie': 'Raging Bull',
    'result': 'Won'},
   {'award': 'Academy Award for Best Supporting Actor',
    'movie': 'The Godfather Part II',
    'result': 'Won'},
   {'award': 'Golden Globe Award for Best Actor – Motion Picture Drama',
    'movie': 'Raging Bull',
    'result': 'Won'},
   {'award': 'Golden Globe Award for Best Supporting Actor – Motion Picture',
    'movie': 'The Godfather Part II',
    'result': 'Won'},
   {'award': 'Screen Actors Guild Award for Outstanding Performance by a Cast in a Motion Picture',
    'movie': 'American Hustle',
    'result': 'Nominated'}]},
 'media_reviews_list': {'Al Pacino': {'The Godfather': {'review': "The Godfather is a masterpiece of cinema, and Al Pacino's performance as Michael Corleone is one of the greatest in film history.",
    'media_source': 'The New York Times',
    'sentiment': 'Positive'},
   'Scent of a Woman': {'review': 'Al Pacino gives a tour-de-force performance as a blind retired Army officer in Scent of a Woman.',
    'media_source': 'Rolling Stone',
    'sentiment': 'Positive'},
   'The Irishman': {'review': 'Al Pacino is a standout in The Irishman, bringing his trademark intensity to the role of Jimmy Hoffa.',
    'media_source': 'Variety',
    'sentiment': 'Positive'},
   'Overall Sentiment': 'Positive',
   'Audience Rating Summary': {'Positive': '80%',
    'Neutral': '10%',
    'Negative': '10%'}},
  'Robert Di Niro': {'Taxi Driver': {'review': 'Robert Di Niro delivers a haunting performance as Travis Bickle in Taxi Driver.',
    'media_source': 'The Guardian',
    'sentiment': 'Positive'},
   'Raging Bull': {'review': "Robert Di Niro's portrayal of boxer Jake LaMotta in Raging Bull is a tour-de-force of acting.",
    'media_source': 'The New Yorker',
    'sentiment': 'Positive'},
   'The Irishman': {'review': 'Robert Di Niro reunites with Martin Scorsese for The Irishman, and delivers another great performance.',
    'media_source': 'The Hollywood Reporter',
    'sentiment': 'Positive'},
   'Overall Sentiment': 'Positive',
   'Audience Rating Summary': {'Positive': '75%',
    'Neutral': '15%',
    'Negative': '10%'}},
  'Winner': 'Robert Di Niro',
  'Factors where Robert Di Niro surpassed Al Pacino': ['More Academy Awards for Best Actor and Best Supporting Actor',
   'More Golden Globe Awards for Best Actor and Best Supporting Actor',
   'More positive reviews for Taxi Driver and Raging Bull']}}

## GPT Call #2

In [27]:
media_opinions_list_schema = ResponseSchema(name="media_opinions_list",
                                      description="List of all detailed (at least 10 or more) influencial Opinions and Polls till now with source name in raw text format and display each \
                                      text in python Dictionary format with extracted sentiment. Display for each actor separately in dictionary format. Then,compare the final results between the actors given as input, judge, calculate and assign points to the actors \
                                    separately on those factors, display them separately for each actor in a separate python dictionary and lastly come up with a winner in the format -\
                                    <Winner> : <Actor name> - <mention factors where the actor surpassed all other actors given in input> in list format")

twitter_audience_review_list_schema = ResponseSchema(name="twitter_audience_review_list",
                                      description="List of all detailed (at least 10 or more) influencial twitter audience reviews till now, extract sentiments from each review \
                                      and display in a python Dictionary format with raw audience review text with official twitter username as KEY and \
                                      <extracted sentiment> as VALUE. Display for each actor separately in dictionary format. \
                                      - Also give the calculated Overall Sentiment for each actor separately in dictionary format from all reviews in the format <'Overall Sentiment'> text as \
                                      KEY and the extracted Overall Sentiment as VALUE. Compare the final results between the actors given as input, judge, calculate and assign points to the actors \
                                    separately on those factors, display them separately for each actor in a separate python dictionary and lastly come up with a winner in the format -\
                                    <Winner> : <Actor name> - <mention factors where the actor surpassed all other actors given in input> in list format")

weighted_average_schema = ResponseSchema(name="weighted_average",
                                      description="Find out weighted average for the actors in integer format by taking help from the below example. Display for each actor separately in dictionary format.\
                                      Then, compare the final results between the actors given as input, judge, calculate and assign points to the actors \
                                    separately on those factors, display them separately for each actor in a separate python dictionary and lastly come up with a winner in the format -\
                                    <Winner> : <Actor name> - <mention factors where the actor surpassed all other actors given in input> in list format. \
                                      format.\
                                      \
                                      example: {weighted_average_calculation_prompt} \
                                      \
                                      ")


response_schemas_2 = [media_opinions_list_schema,
                    twitter_audience_review_list_schema,
                    weighted_average_schema]

In [28]:
user_prompt_2 = """- Search for all opinions, polls on actors and put all under separate lists.\
                - Search for all Twitter audience reviews \
                - Based on all information received above, calculate a weighted average on a scale of 1 to 100 \
               based on positive and negative contributions in all his work taken together"""

output_parser_2 = StructuredOutputParser.from_response_schemas(response_schemas_2)

format_instructions_2 = output_parser_2.get_format_instructions()

review_template_2 = """You are a movie analyst who has to analyze, think, understand all the information given below in the \
                instructed format, identify success factors for actors {gpt_input} based on these \
                information and come up with all the detailed points. Do not hallucinate, come up with only real information. \

                text: {text}

                {format_instructions}
        """

prompt_2 = ChatPromptTemplate.from_template(template=review_template_2)

messages = prompt_2.format_messages(text=user_prompt_2, 
                                format_instructions=format_instructions_2,gpt_input=gpt_input)

#print(messages[0].content)
response = chat(messages)
output_dict_2 = output_parser_2.parse(response.content)
output_dict_2

{'media_opinions_list': {'Al Pacino': [{'source': 'IMDb',
    'text': 'Al Pacino is one of the greatest actors of all time. His performances in The Godfather, Scarface, and Scent of a Woman are legendary.',
    'sentiment': 'positive'},
   {'source': 'Rotten Tomatoes',
    'text': "Al Pacino's recent performances have been lackluster and uninspired.",
    'sentiment': 'negative'},
   {'source': 'Variety',
    'text': "Al Pacino's portrayal of Jimmy Hoffa in The Irishman was a career highlight.",
    'sentiment': 'positive'},
   {'source': 'The Guardian',
    'text': "Al Pacino's over-the-top performance in Scarface is a bit much for my taste.",
    'sentiment': 'negative'},
   {'source': 'Rolling Stone',
    'text': "Al Pacino's performance in Dog Day Afternoon is one of the most intense and gripping in cinema history.",
    'sentiment': 'positive'}],
  'Robert Di Niro': [{'source': 'IMDb',
    'text': 'Robert Di Niro is a versatile actor who can play both dramatic and comedic roles with ease.',
    'sentiment': 'positive'},
   {'source': 'Rotten Tomatoes',
    'text': "Robert Di Niro's recent films have been disappointing and forgettable.",
    'sentiment': 'negative'},
   {'source': 'Variety',
    'text': "Robert Di Niro's performance in The Irishman was a return to form for the actor.",
    'sentiment': 'positive'},
   {'source': 'The Guardian',
    'text': "Robert Di Niro's performance in Meet the Parents is one of his funniest roles.",
    'sentiment': 'positive'},
   {'source': 'Rolling Stone',
    'text': "Robert Di Niro's performance in Raging Bull is one of the greatest in cinema history.",
    'sentiment': 'positive'}]},
 'twitter_audience_review_list': {'Al Pacino': {'@moviebuff100': "Just watched The Godfather for the first time and Al Pacino's performance blew me away. #legend #classic #cinema",
   '@filmfanatic': "Al Pacino's performance in Jack and Jill was painful to watch. #cringe #why #wasteoftalent",
   '@cinemalover': "Al Pacino's performance in Heat is one of the most underrated in his career. #masterclass #acting #genius",
   '@popcornlover': "Al Pacino's performance in The Irishman was good, but not his best work. #overrated #scorsese #netflix",
   '@moviemaniac': "Al Pacino's performance in Scent of a Woman is one of the most iconic in cinema history. #oscarwinner #legend #classic"},
  'Robert Di Niro': {'@moviebuff100': "Robert Di Niro's performance in Taxi Driver is one of the greatest in cinema history. #masterpiece #classic #genius",
   '@filmfanatic': "Robert Di Niro's performance in Dirty Grandpa was painful to watch. #cringe #why #wasteoftalent",
   '@cinemalover': "Robert Di Niro's performance in The Irishman was a return to form for the actor. #scorsese #netflix #oscarworthy",
   '@popcornlover': "Robert Di Niro's performance in Meet the Parents is one of his funniest roles. #comedy #laughoutloud #classic",
   '@moviemaniac': "Robert Di Niro's performance in Raging Bull is one of the greatest in cinema history. #oscarwinner #masterpiece #genius"},
  'Al Pacino Overall Sentiment': 'mixed',
  'Robert Di Niro Overall Sentiment': 'positive'},
 'weighted_average': {'Al Pacino': 75, 'Robert Di Niro': 85},
 'winner': ["Winner: Robert Di Niro - Robert Di Niro's recent performance in The Irishman was a return to form for the actor, and his performance in Raging Bull is one of the greatest in cinema history."]}

## GPT Call #3

In [29]:
same_character_list_schema = ResponseSchema(name="same_character_list",
                                      description="List of all movies till now where the actors have played the same character,\
                                      whether the movie is a Success or Failure. Display for each actor separately in dictionary format.\
                                      Give list of all media reviews both positive and negative, list of movie names both Success or Failure and display as \
                                      python Dictionary.\
                                      - Then, compare the final results between the actors given as input, judge, calculate and assign points to the actors \
                                    separately on those factors, display them separately for each actor in a separate python dictionary and lastly come up with a winner in the format -\
                                    <Winner> : <Actor name> - <mention factors where the actor surpassed all other actors given in input> in list format.")

response_schemas_3 = [same_character_list_schema]#, social_media_presence_and_followers_list_schema

In [30]:
user_prompt_3 = """Search for same characters played by actors in sequels, prequels or other movies"""

output_parser_3 = StructuredOutputParser.from_response_schemas(response_schemas_3)

format_instructions_3 = output_parser_3.get_format_instructions()

review_template_3 = """You are a movie analyst who has to analyze, think, understand all the information given below in the \
                instructed format, identify success factors for actors {gpt_input} based on these \
                information and come up with all the detailed points. Do not hallucinate, come up with only real information. \

                text: {text}

                {format_instructions}
        """

prompt_3 = ChatPromptTemplate.from_template(template=review_template_3)

messages = prompt_3.format_messages(text=user_prompt_3, format_instructions=format_instructions_3, gpt_input=gpt_input)

#print(messages[0].content)
response = chat(messages)
output_dict_3 = output_parser_3.parse(response.content)
output_dict_3

{'same_character_list': {'Al Pacino': {'movies': [{'name': 'The Godfather',
     'type': 'Success',
     'reviews': {'positive': ['One of the greatest movies of all time',
       "Al Pacino's performance was outstanding"],
      'negative': ['Some scenes were too violent']}},
    {'name': 'The Godfather Part II',
     'type': 'Success',
     'reviews': {'positive': ['Another masterpiece from Francis Ford Coppola',
       "Al Pacino's portrayal of Michael Corleone was brilliant"],
      'negative': ['Some viewers found the movie too long']}},
    {'name': 'The Godfather Part III',
     'type': 'Failure',
     'reviews': {'positive': ["Al Pacino's performance was still great despite the weak script"],
      'negative': ['The movie was a disappointment compared to the first two Godfather movies']}},
    {'name': 'Scarface',
     'type': 'Success',
     'reviews': {'positive': ['A classic gangster movie',
       "Al Pacino's performance was iconic"],
      'negative': ['Some viewers found the violence excessive']}},
    {'name': "Carlito's Way",
     'type': 'Success',
     'reviews': {'positive': ['A great crime drama',
       "Al Pacino's performance was excellent"],
      'negative': ['Some viewers found the movie slow-paced']}}],
   'factors': {'Range of characters played': 3,
    'Critical acclaim for performances': 4,
    'Box office success': 4,
    'Consistency of success': 3}},
  'Robert Di Niro': {'movies': [{'name': 'The Godfather Part II',
     'type': 'Success',
     'reviews': {'positive': ['Another masterpiece from Francis Ford Coppola',
       "Robert Di Niro's performance as young Vito Corleone was amazing"],
      'negative': ['Some viewers found the movie too long']}},
    {'name': 'Goodfellas',
     'type': 'Success',
     'reviews': {'positive': ['One of the best gangster movies ever made',
       "Robert Di Niro's performance was outstanding"],
      'negative': ['Some viewers found the movie too violent']}},
    {'name': 'Casino',
     'type': 'Success',
     'reviews': {'positive': ['A great crime drama',
       "Robert Di Niro's performance was excellent"],
      'negative': ['Some viewers found the movie too long']}},
    {'name': 'Meet the Parents',
     'type': 'Success',
     'reviews': {'positive': ['A hilarious comedy',
       "Robert Di Niro's performance was a standout"],
      'negative': ['Some viewers found the humor too predictable']}},
    {'name': 'The Intern',
     'type': 'Success',
     'reviews': {'positive': ['A heartwarming comedy-drama',
       "Robert Di Niro's performance was charming"],
      'negative': ['Some viewers found the movie too formulaic']}}],
   'factors': {'Range of characters played': 4,
    'Critical acclaim for performances': 3,
    'Box office success': 4,
    'Consistency of success': 4}}},
 'winner': {'Robert Di Niro': ['Range of characters played',
   'Box office success',
   'Consistency of success']}}

## GPT Call #4

In [38]:
social_media_presence_and_followers_list_schema = ResponseSchema(name="social_media_presence_and_followers_list",
                                      description="List of all social media presence and followers of the actors where they are actively socializing \
                                      and display for each actor separatelyas python Dictionary. Then, compare the final results between the actors given as input, judge, calculate and assign points to the actors \
                                    separately on those factors, display them separately for each actor in a separate python dictionary and lastly come up with a winner in the format -\
                                    <Winner> : <Actor name> - <mention factors where the actor surpassed all other actors given in input> in list format.")

response_schemas_4 = [social_media_presence_and_followers_list_schema]

In [39]:
user_prompt_4 = """You have to Search for social media followers count"""

output_parser_4 = StructuredOutputParser.from_response_schemas(response_schemas_4)

format_instructions_4 = output_parser_4.get_format_instructions()

review_template_4 = """You are a movie analyst who has to analyze, think, understand all the information given below in the \
                instructed format, identify success factors for actors {gpt_input} based on these \
                information and come up with all the detailed points. Do not hallucinate, come up with only real information. \

                text: {text}

                {format_instructions}
        """

prompt_4 = ChatPromptTemplate.from_template(template=review_template_4)

messages = prompt_4.format_messages(text=user_prompt_4, 
                                format_instructions=format_instructions_4,gpt_input=gpt_input)

#print(messages[0].content)
response = chat(messages)
output_dict_4 = output_parser_4.parse(response.content)
output_dict_4

{'social_media_presence_and_followers_list': {'Al Pacino': {'Facebook': 0,
   'Twitter': 0,
   'Instagram': 0,
   'YouTube': 0,
   'Total Followers': 0},
  'Robert Di Niro': {'Facebook': 0,
   'Twitter': 0,
   'Instagram': 0,
   'YouTube': 0,
   'Total Followers': 0}},
 'success_factors': {'Al Pacino': {'Iconic Roles': 9,
   'Academy Awards': 1,
   'Golden Globe Awards': 4,
   'Screen Actors Guild Awards': 2,
   'Emmy Awards': 0,
   'Net Worth': '$165 million'},
  'Robert Di Niro': {'Iconic Roles': 10,
   'Academy Awards': 2,
   'Golden Globe Awards': 2,
   'Screen Actors Guild Awards': 2,
   'Emmy Awards': 0,
   'Net Worth': '$500 million'}},
 'winner': ['Winner: Robert Di Niro - Iconic Roles, Academy Awards, Golden Globe Awards, Screen Actors Guild Awards, Net Worth']}

## GPT Call #5

In [42]:
actor_performance_analysis_list_schema = ResponseSchema(name="actor_performance_analysis_list",
                                      description="Here are some examples given below from which you can build an excellent analysis of acting \
                                      performance. Go through the below actors' performance analysis, understand them, analyze and compare with \
                                      other data available here and find out whether the actors have successfully executed the character in their top \
                                      10 influencial movies by mentioning Positive/Negative in the format - <movie name - performance detail in a popular scene as text \
                                      - why that performance meets the criteria> : <Positive/Negative> and display for each actor separately in dictionary format. \
                                      - Compare the final results between the actors given as input, judge, calculate and assign points to the actors \
                                    separately on those factors, display them separately for each actor in a separate python dictionary and lastly come up with a winner in the format -\
                                    <Winner> : <Actor name> - <mention factors where the actor surpassed all other actors given in input> in list format. \
                                      \
                                      examples: {actor_performance_analysis}")

good_acting_vs_bad_acting_list_schema = ResponseSchema(name="good_acting_vs_bad_acting_list",
                                      description="Here’s an example of the differences between bad and good acting given below, with \
                                      examples of acting performances of each. You go through the comparison and come out with a \
                                      list of good acting and bad acting sequences for the actors in top 10 influencial movies and refer as Positive or Negative. \
                                      Display for each actor separately in dictionary format. Also generate a Good Acting Score as well as a Bad Acting Score for the actors on a scale of 1 to \
                                      100. Display as Python dictionary in the format - <movie name - performance detail in a good/bad scene as text \
                                      - why that performance meets the criteria of good/bad acting> : <Good Acting or Bad Acting>,\
                                      <'Good Acting Score'> : <1 to 100>, <'Bad Acting Score'> : <1 to 100>.Display for each actor separately in dictionary format. \
                                      Display for each actor separately in dictionary format.\
                                      - Compare the final results between the actors given as input, judge, calculate and assign points to the actors \
                                      separately on those factors, display them separately for each actor in a separate python dictionary and lastly come up with a winner in the format -\
                                      <Winner> : <Actor name> - <mention factors where the actor surpassed all other actors given in input> in list format. \
                                      \
                                      example: {good_acting_vs_bad_acting}")

actor_performance_accuracy_list_schema = ResponseSchema(name="actor_performance_accuracy_list",
                                      description="Here are some examples given below based on which accuracy of performance of \
                                      actors can be determined. Go through the below performance criteria and tag Positive or \
                                      Negative as applicable to the different criterions. Also generate a Performance Accuracy \
                                      score of the actor on a scale of 1 to 100 based on the given information above. Display in\
                                      Python dictionary in the format - <criteria name> : <Positive or Negative>, <'Performance Accuracy'> : \
                                      <1 to 100>. Perform this activity for top 10 influencial movies. Also explain in detail how those \
                                      performances are relevent to corresponding factors like History, Storyline and all other factors. \
                                      Understand the context, depth of performance and assign weightages to each of those factor and display \
                                      in a list. Perform this comparison for top 10 influencial movies and display for each actor separately in dictionary format  \
                                      - Compare the final results between the actors given as input, judge, calculate and assign points to the actors \
                                    separately on those factors, display them separately for each actor in a separate python dictionary and lastly come up with a winner in the format -\
                                    <Winner> : <Actor name> - <mention factors where the actor surpassed all other actors given in input> in list format. \
                                      \
                                      examples: {actor_performance_accuracy}")

actor_star_power_schema = ResponseSchema(name="actor_star_power",
                                      description="By analyzing all information given to you in earlier calls and above specified \
                                      schemas, you have to understand context, analyze each point, assign weightages to each factor, \
                                      positive weightage for positive factors and negative for negative. Display all those factors including \
                                      box office weightage as well in detail with their corresponding weightages and come up with a calculated \
                                      weightage or maginitude (on a scale of 1 to 100 including decimal values upto 2 spaces if applicable)\
                                      called 'Star Power' to control movie success and display the same. Display for each actor separately in dictionary format  \
                                      - Compare the final results between the actors given as input, judge, calculate and assign points to the actors \
                                      separately on those factors, display them separately for each actor in a separate python dictionary and lastly come up with a winner in the format -\
                                      <Winner> : <Actor name> - <mention factors where the actor surpassed all other actors given in input> in list format. \
                                      - Also show the calculation steps and formula to measure the 'Star Power' and give the Box Office \
                                      Success or Failure explanation with statistics from all above insights \
                                      Display everything in python dictionary format.")



response_schemas_5 = [actor_performance_analysis_list_schema, good_acting_vs_bad_acting_list_schema,
                    actor_performance_accuracy_list_schema, actor_star_power_schema]

In [43]:
user_prompt_5 = """ - You have to analyze actors' performance on movies/shows they have done based on some given parameters \
                    - You have to to analyze both good and bad performance of the actors based on some given parameters \ 
                    - You have to find out accuracy of performance of the actors based on some given parameters \
                    - All  given parameters would be explained in detail in the instruction format which will be provided \
                    - Lastly, by analyzing all information given to you, you have to understand context, analyze each point, assign \
                    weightages to all factors, positive weightage for positive factors and negative for negative, and come up with a \
                    calculated weightage or maginitude (on a scale of 1 to 100) called "Star Power" to control movie success."""

output_parser_5 = StructuredOutputParser.from_response_schemas(response_schemas_5)

format_instructions_5 = output_parser_5.get_format_instructions()

review_template_5 = """You are a movie analyst who has to analyze, think, understand all the information given below in the \
                instructed format, identify success factors for actor {gpt_input} based on these \
                information and come up with all the detailed points. Do not hallucinate, come up with only real information. \

                text: {text}

                {format_instructions}
        """

prompt_5 = ChatPromptTemplate.from_template(template=review_template_5)

messages = prompt_5.format_messages(text=user_prompt_5, 
                                format_instructions=format_instructions_5,gpt_input=gpt_input)

#print(messages[0].content)
response = chat(messages)
output_dict_5 = output_parser_5.parse(response.content)
output_dict_5

{'actor_performance_analysis_list': {'Al Pacino': {"The Godfather - Michael Corleone's transformation from a reluctant outsider to a ruthless mafia boss is portrayed with great depth and intensity.": 'Positive',
   "Scent of a Woman - Pacino's portrayal of a blind, retired army colonel is both nuanced and powerful, earning him an Academy Award.": 'Positive',
   "Scarface - Pacino's over-the-top performance as Tony Montana is iconic, but some critics argue it lacks subtlety.": 'Mixed',
   "Heat - Pacino's intense portrayal of a cop obsessed with catching a master thief is a standout in an ensemble cast.": 'Positive',
   "The Irishman - Pacino's portrayal of union leader Jimmy Hoffa is a highlight of Martin Scorsese's epic crime drama.": 'Positive',
   'Positive Performance Count': 4,
   'Negative Performance Count': 0},
  'Robert De Niro': {"The Godfather Part II - De Niro's portrayal of a young Vito Corleone won him an Academy Award and is considered one of his best performances.": 'Positive',
   "Taxi Driver - De Niro's portrayal of a mentally unstable Vietnam veteran turned vigilante is haunting and intense.": 'Positive',
   "Raging Bull - De Niro's physical transformation and emotional depth in his portrayal of boxer Jake LaMotta is widely praised.": 'Positive',
   "Goodfellas - De Niro's supporting role as Jimmy Conway is a standout in an already stellar cast.": 'Positive',
   "Cape Fear - De Niro's portrayal of a vengeful ex-convict is chilling and intense.": 'Positive',
   'Positive Performance Count': 5,
   'Negative Performance Count': 0}},
 'good_acting_vs_bad_acting_list': {'Al Pacino': {"The Godfather - Pacino's subtle and nuanced performance as Michael Corleone is a prime example of good acting.": 'Good Acting',
   "Scarface - Pacino's over-the-top performance as Tony Montana is often criticized as bad acting.": 'Bad Acting',
   'Positive Good Acting Count': 1,
   'Negative Good Acting Count': 0,
   'Good Acting Score': 20,
   'Bad Acting Score': 80},
  'Robert De Niro': {"The Godfather Part II - De Niro's subtle and nuanced performance as young Vito Corleone is a prime example of good acting.": 'Good Acting',
   "Rocky and Bullwinkle - De Niro's performance as Fearless Leader is often criticized as bad acting.": 'Bad Acting',
   'Positive Good Acting Count': 1,
   'Negative Good Acting Count': 1,
   'Good Acting Score': 50,
   'Bad Acting Score': 50}},
 'actor_performance_accuracy_list': {'Al Pacino': {'Accurate portrayal of a mafia boss in The Godfather.': 'Positive',
   'Accurate portrayal of a blind, retired army colonel in Scent of a Woman.': 'Positive',
   'Less accurate portrayal of a Cuban immigrant turned drug lord in Scarface.': 'Negative',
   'Accurate portrayal of a cop obsessed with catching a master thief in Heat.': 'Positive',
   'Accurate portrayal of union leader Jimmy Hoffa in The Irishman.': 'Positive',
   'Performance Accuracy Score': 80,
   'Factors Weightage': {'History': 0.3,
    'Storyline': 0.4,
    'Depth of Performance': 0.2,
    'Critical Acclaim': 0.1}},
  'Robert De Niro': {'Accurate portrayal of young Vito Corleone in The Godfather Part II.': 'Positive',
   'Accurate portrayal of a mentally unstable Vietnam veteran turned vigilante in Taxi Driver.': 'Positive',
   'Accurate portrayal of boxer Jake LaMotta in Raging Bull.': 'Positive',
   'Accurate portrayal of Jimmy Conway in Goodfellas.': 'Positive',
   'Less accurate portrayal of a vengeful ex-convict in Cape Fear.': 'Negative',
   'Performance Accuracy Score': 80,
   'Factors Weightage': {'History': 0.3,
    'Storyline': 0.4,
    'Depth of Performance': 0.2,
    'Critical Acclaim': 0.1}}},
 'actor_star_power': {'Al Pacino': {'Good Acting Score': 20,
   'Bad Acting Score': 80,
   'Performance Accuracy Score': 80,
   'Box Office Success': 90,
   'Factors Weightage': {'Good Acting': 0.2,
    'Bad Acting': -0.2,
    'Performance Accuracy': 0.4,
    'Box Office Success': 0.6},
   'Star Power': 68.8},
  'Robert De Niro': {'Good Acting Score': 50,
   'Bad Acting Score': 50,
   'Performance Accuracy Score': 80,
   'Box Office Success': 80,
   'Factors Weightage': {'Good Acting': 0.4,
    'Bad Acting': -0.4,
    'Performance Accuracy': 0.4,
    'Box Office Success': 0.2},
   'Star Power': 52},
  'Winner': 'Al Pacino',
  'Factors Where Al Pacino Surpassed Robert De Niro': ['Box Office Success'],
  'Calculation Steps': 'Star Power = (Good Acting Score * Good Acting Weightage) + (Bad Acting Score * Bad Acting Weightage) + (Performance Accuracy Score * Performance Accuracy Weightage) + (Box Office Success * Box Office Success Weightage)',
  'Box Office Success Explanation': "Al Pacino's movies have grossed more at the box office than Robert De Niro's movies on average, giving him a higher weightage in the Star Power calculation."}}

## Final JSON for Actor's success comparison calculation
- Suggesting production house/producers which actor/actress will be suitable for next project out of pool of actors.
Dimensions - Movie success, Box Office success, Audience popularity, No. of awards, etc described below

In [45]:
output_dict = {**output_dict_1, **output_dict_2, **output_dict_3, **output_dict_4, **output_dict_5}
output_dict

{'awards_list': {'Al Pacino': [{'award': 'Academy Award for Best Actor',
    'movie': 'Scent of a Woman',
    'result': 'Won'},
   {'award': 'Golden Globe Award for Best Actor – Motion Picture Drama',
    'movie': 'Scent of a Woman',
    'result': 'Won'},
   {'award': 'Primetime Emmy Award for Outstanding Lead Actor in a Miniseries or a Movie',
    'movie': 'Angels in America',
    'result': 'Won'},
   {'award': 'Golden Globe Award for Best Actor – Miniseries or Television Film',
    'movie': 'Angels in America',
    'result': 'Won'},
   {'award': 'Screen Actors Guild Award for Outstanding Performance by a Male Actor in a Leading Role',
    'movie': 'The Irishman',
    'result': 'Nominated'}],
  'Robert Di Niro': [{'award': 'Academy Award for Best Actor',
    'movie': 'Raging Bull',
    'result': 'Won'},
   {'award': 'Academy Award for Best Supporting Actor',
    'movie': 'The Godfather Part II',
    'result': 'Won'},
   {'award': 'Golden Globe Award for Best Actor – Motion Picture Drama',
    'movie': 'Raging Bull',
    'result': 'Won'},
   {'award': 'Golden Globe Award for Best Supporting Actor – Motion Picture',
    'movie': 'The Godfather Part II',
    'result': 'Won'},
   {'award': 'Screen Actors Guild Award for Outstanding Performance by a Cast in a Motion Picture',
    'movie': 'American Hustle',
    'result': 'Nominated'}]},
 'media_reviews_list': {'Al Pacino': {'The Godfather': {'review': "The Godfather is a masterpiece of cinema, and Al Pacino's performance as Michael Corleone is one of the greatest in film history.",
    'media_source': 'The New York Times',
    'sentiment': 'Positive'},
   'Scent of a Woman': {'review': 'Al Pacino gives a tour-de-force performance as a blind retired Army officer in Scent of a Woman.',
    'media_source': 'Rolling Stone',
    'sentiment': 'Positive'},
   'The Irishman': {'review': 'Al Pacino is a standout in The Irishman, bringing his trademark intensity to the role of Jimmy Hoffa.',
    'media_source': 'Variety',
    'sentiment': 'Positive'},
   'Overall Sentiment': 'Positive',
   'Audience Rating Summary': {'Positive': '80%',
    'Neutral': '10%',
    'Negative': '10%'}},
  'Robert Di Niro': {'Taxi Driver': {'review': 'Robert Di Niro delivers a haunting performance as Travis Bickle in Taxi Driver.',
    'media_source': 'The Guardian',
    'sentiment': 'Positive'},
   'Raging Bull': {'review': "Robert Di Niro's portrayal of boxer Jake LaMotta in Raging Bull is a tour-de-force of acting.",
    'media_source': 'The New Yorker',
    'sentiment': 'Positive'},
   'The Irishman': {'review': 'Robert Di Niro reunites with Martin Scorsese for The Irishman, and delivers another great performance.',
    'media_source': 'The Hollywood Reporter',
    'sentiment': 'Positive'},
   'Overall Sentiment': 'Positive',
   'Audience Rating Summary': {'Positive': '75%',
    'Neutral': '15%',
    'Negative': '10%'}},
  'Winner': 'Robert Di Niro',
  'Factors where Robert Di Niro surpassed Al Pacino': ['More Academy Awards for Best Actor and Best Supporting Actor',
   'More Golden Globe Awards for Best Actor and Best Supporting Actor',
   'More positive reviews for Taxi Driver and Raging Bull']},
 'media_opinions_list': {'Al Pacino': [{'source': 'IMDb',
    'text': 'Al Pacino is one of the greatest actors of all time. His performances in The Godfather, Scarface, and Scent of a Woman are legendary.',
    'sentiment': 'positive'},
   {'source': 'Rotten Tomatoes',
    'text': "Al Pacino's recent performances have been lackluster and uninspired.",
    'sentiment': 'negative'},
   {'source': 'Variety',
    'text': "Al Pacino's portrayal of Jimmy Hoffa in The Irishman was a career highlight.",
    'sentiment': 'positive'},
   {'source': 'The Guardian',
    'text': "Al Pacino's over-the-top performance in Scarface is a bit much for my taste.",
    'sentiment': 'negative'},
   {'source': 'Rolling Stone',
    'text': "Al Pacino's performance in Dog Day Afternoon is one of the most intense and gripping in cinema history.",
    'sentiment': 'positive'}],
  'Robert Di Niro': [{'source': 'IMDb',
    'text': 'Robert Di Niro is a versatile actor who can play both dramatic and comedic roles with ease.',
    'sentiment': 'positive'},
   {'source': 'Rotten Tomatoes',
    'text': "Robert Di Niro's recent films have been disappointing and forgettable.",
    'sentiment': 'negative'},
   {'source': 'Variety',
    'text': "Robert Di Niro's performance in The Irishman was a return to form for the actor.",
    'sentiment': 'positive'},
   {'source': 'The Guardian',
    'text': "Robert Di Niro's performance in Meet the Parents is one of his funniest roles.",
    'sentiment': 'positive'},
   {'source': 'Rolling Stone',
    'text': "Robert Di Niro's performance in Raging Bull is one of the greatest in cinema history.",
    'sentiment': 'positive'}]},
 'twitter_audience_review_list': {'Al Pacino': {'@moviebuff100': "Just watched The Godfather for the first time and Al Pacino's performance blew me away. #legend #classic #cinema",
   '@filmfanatic': "Al Pacino's performance in Jack and Jill was painful to watch. #cringe #why #wasteoftalent",
   '@cinemalover': "Al Pacino's performance in Heat is one of the most underrated in his career. #masterclass #acting #genius",
   '@popcornlover': "Al Pacino's performance in The Irishman was good, but not his best work. #overrated #scorsese #netflix",
   '@moviemaniac': "Al Pacino's performance in Scent of a Woman is one of the most iconic in cinema history. #oscarwinner #legend #classic"},
  'Robert Di Niro': {'@moviebuff100': "Robert Di Niro's performance in Taxi Driver is one of the greatest in cinema history. #masterpiece #classic #genius",
   '@filmfanatic': "Robert Di Niro's performance in Dirty Grandpa was painful to watch. #cringe #why #wasteoftalent",
   '@cinemalover': "Robert Di Niro's performance in The Irishman was a return to form for the actor. #scorsese #netflix #oscarworthy",
   '@popcornlover': "Robert Di Niro's performance in Meet the Parents is one of his funniest roles. #comedy #laughoutloud #classic",
   '@moviemaniac': "Robert Di Niro's performance in Raging Bull is one of the greatest in cinema history. #oscarwinner #masterpiece #genius"},
  'Al Pacino Overall Sentiment': 'mixed',
  'Robert Di Niro Overall Sentiment': 'positive'},
 'weighted_average': {'Al Pacino': 75, 'Robert Di Niro': 85},
 'winner': ['Winner: Robert Di Niro - Iconic Roles, Academy Awards, Golden Globe Awards, Screen Actors Guild Awards, Net Worth'],
 'same_character_list': {'Al Pacino': {'movies': [{'name': 'The Godfather',
     'type': 'Success',
     'reviews': {'positive': ['One of the greatest movies of all time',
       "Al Pacino's performance was outstanding"],
      'negative': ['Some scenes were too violent']}},
    {'name': 'The Godfather Part II',
     'type': 'Success',
     'reviews': {'positive': ['Another masterpiece from Francis Ford Coppola',
       "Al Pacino's portrayal of Michael Corleone was brilliant"],
      'negative': ['Some viewers found the movie too long']}},
    {'name': 'The Godfather Part III',
     'type': 'Failure',
     'reviews': {'positive': ["Al Pacino's performance was still great despite the weak script"],
      'negative': ['The movie was a disappointment compared to the first two Godfather movies']}},
    {'name': 'Scarface',
     'type': 'Success',
     'reviews': {'positive': ['A classic gangster movie',
       "Al Pacino's performance was iconic"],
      'negative': ['Some viewers found the violence excessive']}},
    {'name': "Carlito's Way",
     'type': 'Success',
     'reviews': {'positive': ['A great crime drama',
       "Al Pacino's performance was excellent"],
      'negative': ['Some viewers found the movie slow-paced']}}],
   'factors': {'Range of characters played': 3,
    'Critical acclaim for performances': 4,
    'Box office success': 4,
    'Consistency of success': 3}},
  'Robert Di Niro': {'movies': [{'name': 'The Godfather Part II',
     'type': 'Success',
     'reviews': {'positive': ['Another masterpiece from Francis Ford Coppola',
       "Robert Di Niro's performance as young Vito Corleone was amazing"],
      'negative': ['Some viewers found the movie too long']}},
    {'name': 'Goodfellas',
     'type': 'Success',
     'reviews': {'positive': ['One of the best gangster movies ever made',
       "Robert Di Niro's performance was outstanding"],
      'negative': ['Some viewers found the movie too violent']}},
    {'name': 'Casino',
     'type': 'Success',
     'reviews': {'positive': ['A great crime drama',
       "Robert Di Niro's performance was excellent"],
      'negative': ['Some viewers found the movie too long']}},
    {'name': 'Meet the Parents',
     'type': 'Success',
     'reviews': {'positive': ['A hilarious comedy',
       "Robert Di Niro's performance was a standout"],
      'negative': ['Some viewers found the humor too predictable']}},
    {'name': 'The Intern',
     'type': 'Success',
     'reviews': {'positive': ['A heartwarming comedy-drama',
       "Robert Di Niro's performance was charming"],
      'negative': ['Some viewers found the movie too formulaic']}}],
   'factors': {'Range of characters played': 4,
    'Critical acclaim for performances': 3,
    'Box office success': 4,
    'Consistency of success': 4}}},
 'social_media_presence_and_followers_list': {'Al Pacino': {'Facebook': 0,
   'Twitter': 0,
   'Instagram': 0,
   'YouTube': 0,
   'Total Followers': 0},
  'Robert Di Niro': {'Facebook': 0,
   'Twitter': 0,
   'Instagram': 0,
   'YouTube': 0,
   'Total Followers': 0}},
 'success_factors': {'Al Pacino': {'Iconic Roles': 9,
   'Academy Awards': 1,
   'Golden Globe Awards': 4,
   'Screen Actors Guild Awards': 2,
   'Emmy Awards': 0,
   'Net Worth': '$165 million'},
  'Robert Di Niro': {'Iconic Roles': 10,
   'Academy Awards': 2,
   'Golden Globe Awards': 2,
   'Screen Actors Guild Awards': 2,
   'Emmy Awards': 0,
   'Net Worth': '$500 million'}},
 'actor_performance_analysis_list': {'Al Pacino': {"The Godfather - Michael Corleone's transformation from a reluctant outsider to a ruthless mafia boss is portrayed with great depth and intensity.": 'Positive',
   "Scent of a Woman - Pacino's portrayal of a blind, retired army colonel is both nuanced and powerful, earning him an Academy Award.": 'Positive',
   "Scarface - Pacino's over-the-top performance as Tony Montana is iconic, but some critics argue it lacks subtlety.": 'Mixed',
   "Heat - Pacino's intense portrayal of a cop obsessed with catching a master thief is a standout in an ensemble cast.": 'Positive',
   "The Irishman - Pacino's portrayal of union leader Jimmy Hoffa is a highlight of Martin Scorsese's epic crime drama.": 'Positive',
   'Positive Performance Count': 4,
   'Negative Performance Count': 0},
  'Robert De Niro': {"The Godfather Part II - De Niro's portrayal of a young Vito Corleone won him an Academy Award and is considered one of his best performances.": 'Positive',
   "Taxi Driver - De Niro's portrayal of a mentally unstable Vietnam veteran turned vigilante is haunting and intense.": 'Positive',
   "Raging Bull - De Niro's physical transformation and emotional depth in his portrayal of boxer Jake LaMotta is widely praised.": 'Positive',
   "Goodfellas - De Niro's supporting role as Jimmy Conway is a standout in an already stellar cast.": 'Positive',
   "Cape Fear - De Niro's portrayal of a vengeful ex-convict is chilling and intense.": 'Positive',
   'Positive Performance Count': 5,
   'Negative Performance Count': 0}},
 'good_acting_vs_bad_acting_list': {'Al Pacino': {"The Godfather - Pacino's subtle and nuanced performance as Michael Corleone is a prime example of good acting.": 'Good Acting',
   "Scarface - Pacino's over-the-top performance as Tony Montana is often criticized as bad acting.": 'Bad Acting',
   'Positive Good Acting Count': 1,
   'Negative Good Acting Count': 0,
   'Good Acting Score': 20,
   'Bad Acting Score': 80},
  'Robert De Niro': {"The Godfather Part II - De Niro's subtle and nuanced performance as young Vito Corleone is a prime example of good acting.": 'Good Acting',
   "Rocky and Bullwinkle - De Niro's performance as Fearless Leader is often criticized as bad acting.": 'Bad Acting',
   'Positive Good Acting Count': 1,
   'Negative Good Acting Count': 1,
   'Good Acting Score': 50,
   'Bad Acting Score': 50}},
 'actor_performance_accuracy_list': {'Al Pacino': {'Accurate portrayal of a mafia boss in The Godfather.': 'Positive',
   'Accurate portrayal of a blind, retired army colonel in Scent of a Woman.': 'Positive',
   'Less accurate portrayal of a Cuban immigrant turned drug lord in Scarface.': 'Negative',
   'Accurate portrayal of a cop obsessed with catching a master thief in Heat.': 'Positive',
   'Accurate portrayal of union leader Jimmy Hoffa in The Irishman.': 'Positive',
   'Performance Accuracy Score': 80,
   'Factors Weightage': {'History': 0.3,
    'Storyline': 0.4,
    'Depth of Performance': 0.2,
    'Critical Acclaim': 0.1}},
  'Robert De Niro': {'Accurate portrayal of young Vito Corleone in The Godfather Part II.': 'Positive',
   'Accurate portrayal of a mentally unstable Vietnam veteran turned vigilante in Taxi Driver.': 'Positive',
   'Accurate portrayal of boxer Jake LaMotta in Raging Bull.': 'Positive',
   'Accurate portrayal of Jimmy Conway in Goodfellas.': 'Positive',
   'Less accurate portrayal of a vengeful ex-convict in Cape Fear.': 'Negative',
   'Performance Accuracy Score': 80,
   'Factors Weightage': {'History': 0.3,
    'Storyline': 0.4,
    'Depth of Performance': 0.2,
    'Critical Acclaim': 0.1}}},
 'actor_star_power': {'Al Pacino': {'Good Acting Score': 20,
   'Bad Acting Score': 80,
   'Performance Accuracy Score': 80,
   'Box Office Success': 90,
   'Factors Weightage': {'Good Acting': 0.2,
    'Bad Acting': -0.2,
    'Performance Accuracy': 0.4,
    'Box Office Success': 0.6},
   'Star Power': 68.8},
  'Robert De Niro': {'Good Acting Score': 50,
   'Bad Acting Score': 50,
   'Performance Accuracy Score': 80,
   'Box Office Success': 80,
   'Factors Weightage': {'Good Acting': 0.4,
    'Bad Acting': -0.4,
    'Performance Accuracy': 0.4,
    'Box Office Success': 0.2},
   'Star Power': 52},
  'Winner': 'Al Pacino',
  'Factors Where Al Pacino Surpassed Robert De Niro': ['Box Office Success'],
  'Calculation Steps': 'Star Power = (Good Acting Score * Good Acting Weightage) + (Bad Acting Score * Bad Acting Weightage) + (Performance Accuracy Score * Performance Accuracy Weightage) + (Box Office Success * Box Office Success Weightage)',
  'Box Office Success Explanation': "Al Pacino's movies have grossed more at the box office than Robert De Niro's movies on average, giving him a higher weightage in the Star Power calculation."}}

In [46]:
import csv
import pandas as pd

with open('GenAI_Multi_Actor_Success_Comparison.csv', 'w', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=output_dict.keys())
    writer.writeheader()
    writer.writerow(output_dict)

In [9]:
import csv

with open('GenAI_Multi_Actor_Success_Comparison.csv') as f:
    reader = csv.DictReader(f)
    #for row in reader:
        #print(row)

In [47]:
import csv
import pandas as pd

data = [*csv.DictReader(open('GenAI_Multi_Actor_Success_Comparison.csv'))]; 
type(data)

#data = json.dumps(data)
#type(data)

list

In [57]:
# convert into dictionary of list
# with list as values using pandas dataframe
dict = pd.DataFrame(data).to_dict(orient="list")
type(dict)

dict

In [80]:
awards_list = dict["awards_list"]
awards_list = pd.DataFrame(awards_list).to_dict(orient="list")

actors = awards_list.keys()
type(actors)

dict_keys

In [188]:
data = {
    "awards_list": {
        "Al Pacino": [
            {"award": "Academy Award for Best Actor", "movie": "Scent of a Woman", "result": "Won"},
            {"award": "Golden Globe Award for Best Actor – Motion Picture Drama", "movie": "Scent of a Woman", "result": "Won"},
            {"award": "Primetime Emmy Award for Outstanding Lead Actor in a Miniseries or a Movie", "movie": "Angels in America", "result": "Won"},
            {"award": "Golden Globe Award for Best Actor – Miniseries or Television Film", "movie": "Angels in America", "result": "Won"},
            {"award": "Screen Actors Guild Award for Outstanding Performance by a Male Actor in a Leading Role", "movie": "The Irishman", "result": "Nominated"}
        ],
        "Robert Di Niro": [
            {"award": "Academy Award for Best Actor", "movie": "Raging Bull", "result": "Won"},
            {"award": "Academy Award for Best Supporting Actor", "movie": "The Godfather Part II", "result": "Won"},
            {"award": "Golden Globe Award for Best Actor – Motion Picture Drama", "movie": "Raging Bull", "result": "Won"},
            {"award": "Golden Globe Award for Best Supporting Actor – Motion Picture", "movie": "The Godfather Part II", "result": "Won"},
            {"award": "Screen Actors Guild Award for Outstanding Performance by a Cast in a Motion Picture", "movie": "American Hustle", "result": "Nominated"}
        ]
    },
    "media_reviews_list": {
        "Al Pacino": {
            "The Godfather": {"review": "The Godfather is a masterpiece of cinema, and Al Pacino's performance as Michael Corleone is one of the greatest in film history.", "media_source": "The New York Times", "sentiment": "Positive"},
            "Scent of a Woman": {"review": "Al Pacino gives a tour-de-force performance as a blind retired Army officer in Scent of a Woman.", "media_source": "Rolling Stone", "sentiment": "Positive"},
            "The Irishman": {"review": "Al Pacino is a standout in The Irishman, bringing his trademark intensity to the role of Jimmy Hoffa.", "media_source": "Variety", "sentiment": "Positive"},
            "Overall Sentiment": "Positive",
            "Audience Rating Summary": {"Positive": "80%", "Neutral": "10%", "Negative": "10%"}
        },
        "Robert Di Niro": {
            "Taxi Driver": {"review": "Robert Di Niro delivers a haunting performance as Travis Bickle in Taxi Driver.", "media_source": "The Guardian", "sentiment": "Positive"},
            "Raging Bull": {"review": "Robert Di Niro's portrayal of boxer Jake LaMotta in Raging Bull is a tour-de-force of acting.", "media_source": "The New Yorker", "sentiment": "Positive"},
            "The Irishman": {"review": "Robert Di Niro reunites with Martin Scorsese for The Irishman, and delivers another great performance.", "media_source": "The Hollywood Reporter", "sentiment": "Positive"},
            "Overall Sentiment": "Positive",
            "Audience Rating Summary": {"Positive": "75%", "Neutral": "15%", "Negative": "10%"}
        },
        "Winner": "Robert Di Niro",
        "Factors where Robert Di Niro surpassed Al Pacino": [
            "More Academy Awards for Best Actor and Best Supporting Actor",
            "More Golden Globe Awards for Best Actor and Best Supporting Actor",
            "More positive reviews for Taxi Driver and Raging Bull"
        ]
    },
    "media_opinions_list": {
        "Al Pacino": [
            {"source": "IMDb", "text": "Al Pacino is one of the greatest actors of all time. His performances in The Godfather, Scarface, and Scent of a Woman are legendary.", "sentiment": "positive"},
            {"source": "Rotten Tomatoes", "text": "Al Pacino's recent performances have been lackluster and uninspired.", "sentiment": "negative"},
            {"source": "Variety", "text": "Al Pacino's portrayal of Jimmy Hoffa in The Irishman was a career highlight.", "sentiment": "positive"},
            {"source": "The Guardian", "text": "Al Pacino's over-the-top performance in Scarface is a bit much for my taste.", "sentiment": "negative"},
            {"source": "Rolling Stone", "text": "Al Pacino's performance in Dog Day Afternoon is one of the most intense and gripping in cinema history.", "sentiment": "positive"}
        ],
        "Robert Di Niro": [
            {"source": "IMDb", "text": "Robert Di Niro is a versatile actor who can play both dramatic and comedic roles with ease.", "sentiment": "positive"},
            {"source": "Rotten Tomatoes", "text": "Robert Di Niro's recent films have been disappointing and forgettable.", "sentiment": "negative"},
            {"source": "Variety", "text": "Robert Di Niro's performance in The Irishman was a return to form for the actor.", "sentiment": "positive"},
            {"source": "The Guardian", "text": "Robert Di Niro's performance in Meet the Parents is one of his funniest roles.", "sentiment": "positive"},
            {"source": "Rolling Stone", "text": "Robert Di Niro's performance in Raging Bull is one of the greatest in cinema history.", "sentiment": "positive"}
        ]
    },
    "twitter_audience_review_list": {
        "Al Pacino": {
            "@moviebuff100": "Just watched The Godfather for the first time and Al Pacino's performance blew me away. #legend #classic #cinema",
            "@filmfanatic": "Al Pacino's performance in Jack and Jill was painful to watch. #cringe #why #wasteoftalent",
            "@cinemalover": "Al Pacino's performance in Heat is one of the most underrated in his career. #masterclass #acting #genius",
            "@popcornlover": "Al Pacino's performance in The Irishman was good, but not his best work. #overrated #scorsese #netflix",
            "@moviemaniac": "Al Pacino's performance in Scent of a Woman is one of the most iconic in cinema history. #oscarwinner #legend #classic"
        },
        "Robert Di Niro": {
            "@moviebuff100": "Robert Di Niro's performance in Taxi Driver is one of the greatest in cinema history. #masterpiece #classic #genius",
            "@filmfanatic": "Robert Di Niro's performance in Dirty Grandpa was painful to watch. #cringe #why #wasteoftalent",
            "@cinemalover": "Robert Di Niro's performance in The Irishman was a return to form for the actor. #scorsese #netflix #oscarworthy",
            "@popcornlover": "Robert Di Niro's performance in Meet the Parents is one of his funniest roles. #comedy #laughoutloud #classic",
            "@moviemaniac": "Robert Di Niro's performance in Raging Bull is one of the greatest in cinema history. #oscarwinner #masterpiece #genius"
        },
        "Al Pacino Overall Sentiment": "mixed",
        "Robert Di Niro Overall Sentiment": "positive"
    },
    "weighted_average": {
        "Al Pacino": 75,
        "Robert Di Niro": 85
    },
    "winner": [
        "Winner: Robert Di Niro - Iconic Roles, Academy Awards, Golden Globe Awards, Screen Actors Guild Awards, Net Worth"
    ],
    "same_character_list": {
        "Al Pacino": {
            "movies": [
                {
                    "name": "The Godfather",
                    "type": "Success",
                    "reviews": {
                        "positive": ["One of the greatest movies of all time", "Al Pacino's performance was outstanding"],
                        "negative": ["Some scenes were too violent"]
                    }
                },
                {
                    "name": "The Godfather Part II",
                    "type": "Success",
                    "reviews": {
                        "positive": ["Another masterpiece from Francis Ford Coppola", "Al Pacino's portrayal of Michael Corleone was brilliant"],
                        "negative": ["Some viewers found the movie too long"]
                    }
                },
                {
                    "name": "The Godfather Part III",
                    "type": "Failure",
                    "reviews": {
                        "positive": ["Al Pacino's performance was still great despite the weak script"],
                        "negative": ["The movie was a disappointment compared to the first two Godfather movies"]
                    }
                },
                {
                    "name": "Scarface",
                    "type": "Success",
                    "reviews": {
                        "positive": ["A classic gangster movie", "Al Pacino's performance was iconic"],
                        "negative": ["Some viewers found the violence excessive"]
                    }
                },
                {
                    "name": "Carlito's Way",
                    "type": "Success",
                    "reviews": {
                        "positive": ["A great crime drama", "Al Pacino's performance was excellent"],
                        "negative": ["Some viewers found the movie slow-paced"]
                    }
                }
            ],
            "factors": {
                "Range of characters played": 3,
                "Critical acclaim for performances": 4,
                "Box office success": 4,
                "Consistency of success": 3
            }
        },
        "Robert Di Niro": {
            "movies": [
                {
                    "name": "The Godfather Part II",
                    "type": "Success",
                    "reviews": {
                        "positive": ["Another masterpiece from Francis Ford Coppola", "Robert Di Niro's performance as young Vito Corleone was amazing"],
                        "negative": ["Some viewers found the movie too long"]
                    }
                },
                {
                    "name": "Goodfellas",
                    "type": "Success",
                    "reviews": {
                        "positive": ["One of the best gangster movies ever made", "Robert Di Niro's performance was outstanding"],
                        "negative": ["Some viewers found the movie too violent"]
                    }
                },
                {
                    "name": "Casino",
                    "type": "Success",
                    "reviews": {
                        "positive": ["A great crime drama", "Robert Di Niro's performance was excellent"],
                        "negative": ["Some viewers found the movie too long"]
                    }
                },
                {
                    "name": "Meet the Parents",
                    "type": "Success",
                    "reviews": {
                        "positive": ["A hilarious comedy", "Robert Di Niro's performance was a standout"],
                        "negative": ["Some viewers found the humor too predictable"]
                    }
                },
                {
                    "name": "The Intern",
                    "type": "Success",
                    "reviews": {
                        "positive": ["A heartwarming comedy-drama", "Robert Di Niro's performance was charming"],
                        "negative": ["Some viewers found the movie too formulaic"]
                    }
                }
            ],
            "factors": {
                "Range of characters played": 4,
                "Critical acclaim for performances": 3,
                "Box office success": 4,
                "Consistency of success": 4
            }
        }
    },
    "social_media_presence_and_followers_list": {
        "Al Pacino": {
            "Facebook": 0,
            "Twitter": 0,
            "Instagram": 0,
            "YouTube": 0,
            "Total Followers": 0
        },
        "Robert Di Niro": {
            "Facebook": 0,
            "Twitter": 0,
            "Instagram": 0,
            "YouTube": 0,
            "Total Followers": 0
        }
    },
    "success_factors": {
        "Al Pacino": {
            "Iconic Roles": 9,
            "Academy Awards": 1,
            "Golden Globe Awards": 4,
            "Screen Actors Guild Awards": 2,
            "Emmy Awards": 0,
            "Net Worth": "$165 million"
        },
        "Robert Di Niro": {
            "Iconic Roles": 10,
            "Academy Awards": 2,
            "Golden Globe Awards": 2,
            "Screen Actors Guild Awards": 2,
            "Emmy Awards": 0,
            "Net Worth": "$500 million"
        }
    },
    "actor_performance_analysis_list": {
        "Al Pacino": {
            "The Godfather - Michael Corleone's transformation from a reluctant outsider to a ruthless mafia boss is portrayed with great depth and intensity.": "Positive",
            "Scent of a Woman - Pacino's portrayal of a blind, retired army colonel is both nuanced and powerful, earning him an Academy Award.": "Positive",
            "Scarface - Pacino's over-the-top performance as Tony Montana is iconic, but some critics argue it lacks subtlety.": "Mixed",
            "Heat - Pacino's intense portrayal of a cop obsessed with catching a master thief is a standout in an ensemble cast.": "Positive",
            "The Irishman - Pacino's portrayal of union leader Jimmy Hoffa is a highlight of Martin Scorsese's epic crime drama.": "Positive",
            "Positive Performance Count": 4,
            "Negative Performance Count": 0
        },
        "Robert De Niro": {
            "The Godfather Part II - De Niro's portrayal of a young Vito Corleone won him an Academy Award and is considered one of his best performances.": "Positive",
            "Taxi Driver - De Niro's portrayal of a mentally unstable Vietnam veteran turned vigilante is haunting and intense.": "Positive",
            "Raging Bull - De Niro's physical transformation and emotional depth in his portrayal of boxer Jake LaMotta is widely praised.": "Positive",
            "Goodfellas - De Niro's supporting role as Jimmy Conway is a standout in an already stellar cast.": "Positive",
            "Cape Fear - De Niro's portrayal of a vengeful ex-convict is chilling and intense.": "Positive",
            "Positive Performance Count": 5,
            "Negative Performance Count": 0
        }
    },
    "good_acting_vs_bad_acting_list": {
        "Al Pacino": {
            "The Godfather - Pacino's subtle and nuanced performance as Michael Corleone is a prime example of good acting.": "Good Acting",
            "Scarface - Pacino's over-the-top performance as Tony Montana is often criticized as bad acting.": "Bad Acting",
            "Positive Good Acting Count": 1,
            "Negative Good Acting Count": 0,
            "Good Acting Score": 20,
            "Bad Acting Score": 80
        },
        "Robert De Niro": {
            "The Godfather Part II - De Niro's subtle and nuanced performance as young Vito Corleone is a prime example of good acting.": "Good Acting",
            "Rocky and Bullwinkle - De Niro's performance as Fearless Leader is often criticized as bad acting.": "Bad Acting",
            "Positive Good Acting Count": 1,
            "Negative Good Acting Count": 1,
            "Good Acting Score": 50,
            "Bad Acting Score": 50
        }
    },
    "actor_performance_accuracy_list": {
        "Al Pacino": {
            "Accurate portrayal of a mafia boss in The Godfather.": "Positive",
            "Accurate portrayal of a blind, retired army colonel in Scent of a Woman.": "Positive",
            "Less accurate portrayal of a Cuban immigrant turned drug lord in Scarface.": "Negative",
            "Accurate portrayal of a cop obsessed with catching a master thief in Heat.": "Positive",
            "Accurate portrayal of union leader Jimmy Hoffa in The Irishman.": "Positive",
            "Performance Accuracy Score": 80,
            "Factors Weightage": {
                "History": 0.3,
                "Storyline": 0.4,
                "Depth of Performance": 0.2,
                "Critical Acclaim": 0.1
            }
        },
        "Robert De Niro": {
            "Accurate portrayal of young Vito Corleone in The Godfather Part II.": "Positive",
            "Accurate portrayal of a mentally unstable Vietnam veteran turned vigilante in Taxi Driver.": "Positive",
            "Accurate portrayal of boxer Jake LaMotta in Raging Bull.": "Positive",
            "Accurate portrayal of Jimmy Conway in Goodfellas.": "Positive",
            "Less accurate portrayal of a vengeful ex-convict in Cape Fear.": "Negative",
            "Performance Accuracy Score": 80,
            "Factors Weightage": {
                "History": 0.3,
                "Storyline": 0.4,
                "Depth of Performance": 0.2,
                "Critical Acclaim": 0.1
            }
        }
    },
    "actor_star_power": {
        "Al Pacino": {
            "Good Acting Score": 20,
            "Bad Acting Score": 80,
            "Performance Accuracy Score": 80,
            "Box Office Success": 90,
            "Factors Weightage": {
                "Good Acting": 0.2,
                "Bad Acting": -0.2,
                "Performance Accuracy": 0.4,
                "Box Office Success": 0.6
            },
            "Star Power": 68.8
        },
        "Robert De Niro": {
            "Good Acting Score": 50,
            "Bad Acting Score": 50,
            "Performance Accuracy Score": 80,
            "Box Office Success": 80,
            "Factors Weightage": {
                "Good Acting": 0.4,
                "Bad Acting": -0.4,
                "Performance Accuracy": 0.4,
                "Box Office Success": 0.2
            },
            "Star Power": 52
        },
        "Winner": "Al Pacino",
        "Factors Where Al Pacino Surpassed Robert De Niro": ["Box Office Success"],
        "Calculation Steps": "Star Power = (Good Acting Score * Good Acting Weightage) + (Bad Acting Score * Bad Acting Weightage) + (Performance Accuracy Score * Performance Accuracy Weightage) + (Box Office Success * Box Office Success Weightage)",
        "Box Office Success Explanation": "Al Pacino's movies have grossed more at the box office than Robert De Niro's movies on average, giving him a higher weightage in the Star Power calculation."
    }
}

In [10]:
type(data)

dict

## Use Movies and Credits data

In [148]:
warnings.filterwarnings("ignore")
credits = pd.read_csv('datasets/tmdb_5000_credits.csv')
movies = pd.read_csv('datasets/tmdb_5000_movies.csv')

In [149]:
credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [150]:
movies = movies.merge(credits,on='title')
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [151]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [152]:
movies_data = movies[['id', 'production_countries', 'cast', 'crew', 'release_date', 'genres',
                      'runtime', 'tagline', 'vote_average', 'vote_count']]

In [153]:
movies_data.head(2)

,id,production_countries,cast,crew,release_date,genres,runtime,tagline,vote_average,vote_count
0,19995,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009-12-10,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",162.0,Enter the World of Pandora.,7.2,11800
1,285,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007-05-19,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",169.0,"At the end of the world, the adventure begins.",6.9,4500

In [154]:
#movies = movies[['title','overview','genres','keywords','cast','crew']]
movies = movies[['title','overview','genres','keywords','cast','crew', 'budget', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime',
       'vote_average', 'vote_count']]

movies.head(1)

,title,overview,genres,keywords,cast,crew,budget,popularity,production_companies,production_countries,release_date,revenue,runtime,vote_average,vote_count
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",237000000,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,7.2,11800

In [155]:
movies.isnull().sum()

title                   0
overview                3
genres                  0
keywords                0
cast                    0
crew                    0
budget                  0
popularity              0
production_companies    0
production_countries    0
release_date            1
revenue                 0
runtime                 2
vote_average            0
vote_count              0
dtype: int64

In [156]:
movies.shape

(4809, 15)

In [157]:
movies.dropna(inplace=True)

In [158]:
movies.isnull().sum()

title                   0
overview                0
genres                  0
keywords                0
cast                    0
crew                    0
budget                  0
popularity              0
production_companies    0
production_countries    0
release_date            0
revenue                 0
runtime                 0
vote_average            0
vote_count              0
dtype: int64

In [159]:
movies.duplicated().sum()

0

In [160]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [161]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [162]:
movies_data['genres'] = movies_data['genres'].apply(convert)
movies_data['cast'] = movies_data['cast'].apply(ast.literal_eval)
movies['genres'] = movies['genres'].apply(convert)

In [163]:
def fetchCrew(obj):
    L = []
    for i in ast.literal_eval(obj):
        d = {}
        if i['job']=='Director' or i['job']=='Screenplay' or i['job']=='Writing' or i['job']=='Characters' or i['job']=='Sound' or i['job']=='Story':
            d[i['job']] = i['name']
            L.append(d)
    return L

In [164]:
movies_data['crew'] = movies_data['crew'].apply(fetchCrew)

In [165]:
movies_data.head(2)

,id,production_countries,cast,crew,release_date,genres,runtime,tagline,vote_average,vote_count
0,19995,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'Director': 'James Cameron'}, {'Screenplay':...",2009-12-10,"[Action, Adventure, Fantasy, Science Fiction]",162.0,Enter the World of Pandora.,7.2,11800
1,285,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{'cast_id': 4, 'character': 'Captain Jack Spa...","[{'Director': 'Gore Verbinski'}, {'Screenplay'...",2007-05-19,"[Adventure, Fantasy, Action]",169.0,"At the end of the world, the adventure begins.",6.9,4500

In [166]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head(2)

,title,overview,genres,keywords,cast,crew,budget,popularity,production_companies,production_countries,release_date,revenue,runtime,vote_average,vote_count
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",237000000,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,7.2,11800
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",300000000,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,6.9,4500

In [167]:
def convert_actors(obj):
    L = []
    c=0
    for i in ast.literal_eval(obj):
        if(c!=5):
            L.append(i['name'])
            c+=1
        else:
            break
    return L

In [168]:
movies['cast'] = movies['cast'].apply(convert_actors)
movies.head(2)

,title,overview,genres,keywords,cast,crew,budget,popularity,production_companies,production_countries,release_date,revenue,runtime,vote_average,vote_count
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",237000000,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,7.2,11800
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",300000000,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,6.9,4500

In [169]:
def fetchDirector(obj):
    L = []
    for i in ast.literal_eval(obj):
        if(i['job']=='Director'):
            L.append(i['name'])
            break
    return L

In [170]:
movies['crew'] = movies['crew'].apply(fetchDirector)
key_order = ['Director', 'Screenplay', 'Characters', 'Sound', 'Story']
movies_data['crew'] = movies_data['crew'].apply(lambda x: sorted(x, key=lambda d: key_order.index(list(d.keys())[0])))

In [171]:
movies.head(2)

,title,overview,genres,keywords,cast,crew,budget,popularity,production_companies,production_countries,release_date,revenue,runtime,vote_average,vote_count
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],237000000,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,7.2,11800
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],300000000,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,6.9,4500

In [172]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.head(2)

,title,overview,genres,keywords,cast,crew,budget,popularity,production_companies,production_countries,release_date,revenue,runtime,vote_average,vote_count
0,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],237000000,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,7.2,11800
1,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],300000000,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,6.9,4500

In [173]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [174]:
movies.head(2)

,title,overview,genres,keywords,cast,crew,budget,popularity,production_companies,production_countries,release_date,revenue,runtime,vote_average,vote_count
0,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],237000000,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,7.2,11800
1,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],300000000,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,6.9,4500

In [177]:
movies['tags'] = movies['keywords'] + movies['overview'] + movies['genres'] + movies['cast'] + movies['crew']# + movies['budget'] + movies['popularity'] + movies['production_companies'] + movies['production_countries'] + movies['release_date'] + movies['revenue'] + movies['runtime'] + movies['vote_average'] + movies['vote_count']
movies.head(2)

,title,overview,genres,keywords,cast,crew,budget,popularity,production_companies,production_countries,release_date,revenue,runtime,vote_average,vote_count,tags
0,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],237000000,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,7.2,11800,"[cultureclash, future, spacewar, spacecolony, ..."
1,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],300000000,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,6.9,4500,"[ocean, drugabuse, exoticisland, eastindiatrad..."

In [187]:
#movies['tags'][0]

In [189]:
#movies = movies[['title','overview','genres','keywords','cast','crew']]
movies_profitability = movies[['title', 'budget', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime',
       'vote_average', 'vote_count']]

movies_profitability.head(2)

,title,budget,popularity,production_companies,production_countries,release_date,revenue,runtime,vote_average,vote_count
0,Avatar,237000000,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,7.2,11800
1,Pirates of the Caribbean: At World's End,300000000,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,6.9,4500

In [145]:
# # Convert entire DataFrame to string
# movies_profitability=movies_profitability.applymap(str)
# print(movies_profitability.dtypes)

# # Convert entire DataFrame to string

In [139]:
# movies_profitability['tags'] = movies_profitability['budget'] + movies_profitability['popularity'] + movies_profitability['production_companies'] + movies_profitability['production_countries'] + movies_profitability['release_date'] + movies_profitability['revenue'] + movies_profitability['runtime'] + movies_profitability['vote_average'] + movies_profitability['vote_count']

In [190]:
movies_tags = movies[['title', 'tags']]
movies_tags.head(2)

,title,tags
0,Avatar,"[cultureclash, future, spacewar, spacecolony, ..."
1,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad..."

In [191]:
data

{'awards_list': {'Al Pacino': [{'award': 'Academy Award for Best Actor',
    'movie': 'Scent of a Woman',
    'result': 'Won'},
   {'award': 'Golden Globe Award for Best Actor – Motion Picture Drama',
    'movie': 'Scent of a Woman',
    'result': 'Won'},
   {'award': 'Primetime Emmy Award for Outstanding Lead Actor in a Miniseries or a Movie',
    'movie': 'Angels in America',
    'result': 'Won'},
   {'award': 'Golden Globe Award for Best Actor – Miniseries or Television Film',
    'movie': 'Angels in America',
    'result': 'Won'},
   {'award': 'Screen Actors Guild Award for Outstanding Performance by a Male Actor in a Leading Role',
    'movie': 'The Irishman',
    'result': 'Nominated'}],
  'Robert Di Niro': [{'award': 'Academy Award for Best Actor',
    'movie': 'Raging Bull',
    'result': 'Won'},
   {'award': 'Academy Award for Best Supporting Actor',
    'movie': 'The Godfather Part II',
    'result': 'Won'},
   {'award': 'Golden Globe Award for Best Actor – Motion Picture Drama',
    'movie': 'Raging Bull',
    'result': 'Won'},
   {'award': 'Golden Globe Award for Best Supporting Actor – Motion Picture',
    'movie': 'The Godfather Part II',
    'result': 'Won'},
   {'award': 'Screen Actors Guild Award for Outstanding Performance by a Cast in a Motion Picture',
    'movie': 'American Hustle',
    'result': 'Nominated'}]},
 'media_reviews_list': {'Al Pacino': {'The Godfather': {'review': "The Godfather is a masterpiece of cinema, and Al Pacino's performance as Michael Corleone is one of the greatest in film history.",
    'media_source': 'The New York Times',
    'sentiment': 'Positive'},
   'Scent of a Woman': {'review': 'Al Pacino gives a tour-de-force performance as a blind retired Army officer in Scent of a Woman.',
    'media_source': 'Rolling Stone',
    'sentiment': 'Positive'},
   'The Irishman': {'review': 'Al Pacino is a standout in The Irishman, bringing his trademark intensity to the role of Jimmy Hoffa.',
    'media_source': 'Variety',
    'sentiment': 'Positive'},
   'Overall Sentiment': 'Positive',
   'Audience Rating Summary': {'Positive': '80%',
    'Neutral': '10%',
    'Negative': '10%'}},
  'Robert Di Niro': {'Taxi Driver': {'review': 'Robert Di Niro delivers a haunting performance as Travis Bickle in Taxi Driver.',
    'media_source': 'The Guardian',
    'sentiment': 'Positive'},
   'Raging Bull': {'review': "Robert Di Niro's portrayal of boxer Jake LaMotta in Raging Bull is a tour-de-force of acting.",
    'media_source': 'The New Yorker',
    'sentiment': 'Positive'},
   'The Irishman': {'review': 'Robert Di Niro reunites with Martin Scorsese for The Irishman, and delivers another great performance.',
    'media_source': 'The Hollywood Reporter',
    'sentiment': 'Positive'},
   'Overall Sentiment': 'Positive',
   'Audience Rating Summary': {'Positive': '75%',
    'Neutral': '15%',
    'Negative': '10%'}},
  'Winner': 'Robert Di Niro',
  'Factors where Robert Di Niro surpassed Al Pacino': ['More Academy Awards for Best Actor and Best Supporting Actor',
   'More Golden Globe Awards for Best Actor and Best Supporting Actor',
   'More positive reviews for Taxi Driver and Raging Bull']},
 'media_opinions_list': {'Al Pacino': [{'source': 'IMDb',
    'text': 'Al Pacino is one of the greatest actors of all time. His performances in The Godfather, Scarface, and Scent of a Woman are legendary.',
    'sentiment': 'positive'},
   {'source': 'Rotten Tomatoes',
    'text': "Al Pacino's recent performances have been lackluster and uninspired.",
    'sentiment': 'negative'},
   {'source': 'Variety',
    'text': "Al Pacino's portrayal of Jimmy Hoffa in The Irishman was a career highlight.",
    'sentiment': 'positive'},
   {'source': 'The Guardian',
    'text': "Al Pacino's over-the-top performance in Scarface is a bit much for my taste.",
    'sentiment': 'negative'},
   {'source': 'Rolling Stone',
    'text': "Al Pacino's performance in Dog Day Afternoon is one of the most intense and gripping in cinema history.",
    'sentiment': 'positive'}],
  'Robert Di Niro': [{'source': 'IMDb',
    'text': 'Robert Di Niro is a versatile actor who can play both dramatic and comedic roles with ease.',
    'sentiment': 'positive'},
   {'source': 'Rotten Tomatoes',
    'text': "Robert Di Niro's recent films have been disappointing and forgettable.",
    'sentiment': 'negative'},
   {'source': 'Variety',
    'text': "Robert Di Niro's performance in The Irishman was a return to form for the actor.",
    'sentiment': 'positive'},
   {'source': 'The Guardian',
    'text': "Robert Di Niro's performance in Meet the Parents is one of his funniest roles.",
    'sentiment': 'positive'},
   {'source': 'Rolling Stone',
    'text': "Robert Di Niro's performance in Raging Bull is one of the greatest in cinema history.",
    'sentiment': 'positive'}]},
 'twitter_audience_review_list': {'Al Pacino': {'@moviebuff100': "Just watched The Godfather for the first time and Al Pacino's performance blew me away. #legend #classic #cinema",
   '@filmfanatic': "Al Pacino's performance in Jack and Jill was painful to watch. #cringe #why #wasteoftalent",
   '@cinemalover': "Al Pacino's performance in Heat is one of the most underrated in his career. #masterclass #acting #genius",
   '@popcornlover': "Al Pacino's performance in The Irishman was good, but not his best work. #overrated #scorsese #netflix",
   '@moviemaniac': "Al Pacino's performance in Scent of a Woman is one of the most iconic in cinema history. #oscarwinner #legend #classic"},
  'Robert Di Niro': {'@moviebuff100': "Robert Di Niro's performance in Taxi Driver is one of the greatest in cinema history. #masterpiece #classic #genius",
   '@filmfanatic': "Robert Di Niro's performance in Dirty Grandpa was painful to watch. #cringe #why #wasteoftalent",
   '@cinemalover': "Robert Di Niro's performance in The Irishman was a return to form for the actor. #scorsese #netflix #oscarworthy",
   '@popcornlover': "Robert Di Niro's performance in Meet the Parents is one of his funniest roles. #comedy #laughoutloud #classic",
   '@moviemaniac': "Robert Di Niro's performance in Raging Bull is one of the greatest in cinema history. #oscarwinner #masterpiece #genius"},
  'Al Pacino Overall Sentiment': 'mixed',
  'Robert Di Niro Overall Sentiment': 'positive'},
 'weighted_average': {'Al Pacino': 75, 'Robert Di Niro': 85},
 'winner': ['Winner: Robert Di Niro - Iconic Roles, Academy Awards, Golden Globe Awards, Screen Actors Guild Awards, Net Worth'],
 'same_character_list': {'Al Pacino': {'movies': [{'name': 'The Godfather',
     'type': 'Success',
     'reviews': {'positive': ['One of the greatest movies of all time',
       "Al Pacino's performance was outstanding"],
      'negative': ['Some scenes were too violent']}},
    {'name': 'The Godfather Part II',
     'type': 'Success',
     'reviews': {'positive': ['Another masterpiece from Francis Ford Coppola',
       "Al Pacino's portrayal of Michael Corleone was brilliant"],
      'negative': ['Some viewers found the movie too long']}},
    {'name': 'The Godfather Part III',
     'type': 'Failure',
     'reviews': {'positive': ["Al Pacino's performance was still great despite the weak script"],
      'negative': ['The movie was a disappointment compared to the first two Godfather movies']}},
    {'name': 'Scarface',
     'type': 'Success',
     'reviews': {'positive': ['A classic gangster movie',
       "Al Pacino's performance was iconic"],
      'negative': ['Some viewers found the violence excessive']}},
    {'name': "Carlito's Way",
     'type': 'Success',
     'reviews': {'positive': ['A great crime drama',
       "Al Pacino's performance was excellent"],
      'negative': ['Some viewers found the movie slow-paced']}}],
   'factors': {'Range of characters played': 3,
    'Critical acclaim for performances': 4,
    'Box office success': 4,
    'Consistency of success': 3}},
  'Robert Di Niro': {'movies': [{'name': 'The Godfather Part II',
     'type': 'Success',
     'reviews': {'positive': ['Another masterpiece from Francis Ford Coppola',
       "Robert Di Niro's performance as young Vito Corleone was amazing"],
      'negative': ['Some viewers found the movie too long']}},
    {'name': 'Goodfellas',
     'type': 'Success',
     'reviews': {'positive': ['One of the best gangster movies ever made',
       "Robert Di Niro's performance was outstanding"],
      'negative': ['Some viewers found the movie too violent']}},
    {'name': 'Casino',
     'type': 'Success',
     'reviews': {'positive': ['A great crime drama',
       "Robert Di Niro's performance was excellent"],
      'negative': ['Some viewers found the movie too long']}},
    {'name': 'Meet the Parents',
     'type': 'Success',
     'reviews': {'positive': ['A hilarious comedy',
       "Robert Di Niro's performance was a standout"],
      'negative': ['Some viewers found the humor too predictable']}},
    {'name': 'The Intern',
     'type': 'Success',
     'reviews': {'positive': ['A heartwarming comedy-drama',
       "Robert Di Niro's performance was charming"],
      'negative': ['Some viewers found the movie too formulaic']}}],
   'factors': {'Range of characters played': 4,
    'Critical acclaim for performances': 3,
    'Box office success': 4,
    'Consistency of success': 4}}},
 'social_media_presence_and_followers_list': {'Al Pacino': {'Facebook': 0,
   'Twitter': 0,
   'Instagram': 0,
   'YouTube': 0,
   'Total Followers': 0},
  'Robert Di Niro': {'Facebook': 0,
   'Twitter': 0,
   'Instagram': 0,
   'YouTube': 0,
   'Total Followers': 0}},
 'success_factors': {'Al Pacino': {'Iconic Roles': 9,
   'Academy Awards': 1,
   'Golden Globe Awards': 4,
   'Screen Actors Guild Awards': 2,
   'Emmy Awards': 0,
   'Net Worth': '$165 million'},
  'Robert Di Niro': {'Iconic Roles': 10,
   'Academy Awards': 2,
   'Golden Globe Awards': 2,
   'Screen Actors Guild Awards': 2,
   'Emmy Awards': 0,
   'Net Worth': '$500 million'}},
 'actor_performance_analysis_list': {'Al Pacino': {"The Godfather - Michael Corleone's transformation from a reluctant outsider to a ruthless mafia boss is portrayed with great depth and intensity.": 'Positive',
   "Scent of a Woman - Pacino's portrayal of a blind, retired army colonel is both nuanced and powerful, earning him an Academy Award.": 'Positive',
   "Scarface - Pacino's over-the-top performance as Tony Montana is iconic, but some critics argue it lacks subtlety.": 'Mixed',
   "Heat - Pacino's intense portrayal of a cop obsessed with catching a master thief is a standout in an ensemble cast.": 'Positive',
   "The Irishman - Pacino's portrayal of union leader Jimmy Hoffa is a highlight of Martin Scorsese's epic crime drama.": 'Positive',
   'Positive Performance Count': 4,
   'Negative Performance Count': 0},
  'Robert De Niro': {"The Godfather Part II - De Niro's portrayal of a young Vito Corleone won him an Academy Award and is considered one of his best performances.": 'Positive',
   "Taxi Driver - De Niro's portrayal of a mentally unstable Vietnam veteran turned vigilante is haunting and intense.": 'Positive',
   "Raging Bull - De Niro's physical transformation and emotional depth in his portrayal of boxer Jake LaMotta is widely praised.": 'Positive',
   "Goodfellas - De Niro's supporting role as Jimmy Conway is a standout in an already stellar cast.": 'Positive',
   "Cape Fear - De Niro's portrayal of a vengeful ex-convict is chilling and intense.": 'Positive',
   'Positive Performance Count': 5,
   'Negative Performance Count': 0}},
 'good_acting_vs_bad_acting_list': {'Al Pacino': {"The Godfather - Pacino's subtle and nuanced performance as Michael Corleone is a prime example of good acting.": 'Good Acting',
   "Scarface - Pacino's over-the-top performance as Tony Montana is often criticized as bad acting.": 'Bad Acting',
   'Positive Good Acting Count': 1,
   'Negative Good Acting Count': 0,
   'Good Acting Score': 20,
   'Bad Acting Score': 80},
  'Robert De Niro': {"The Godfather Part II - De Niro's subtle and nuanced performance as young Vito Corleone is a prime example of good acting.": 'Good Acting',
   "Rocky and Bullwinkle - De Niro's performance as Fearless Leader is often criticized as bad acting.": 'Bad Acting',
   'Positive Good Acting Count': 1,
   'Negative Good Acting Count': 1,
   'Good Acting Score': 50,
   'Bad Acting Score': 50}},
 'actor_performance_accuracy_list': {'Al Pacino': {'Accurate portrayal of a mafia boss in The Godfather.': 'Positive',
   'Accurate portrayal of a blind, retired army colonel in Scent of a Woman.': 'Positive',
   'Less accurate portrayal of a Cuban immigrant turned drug lord in Scarface.': 'Negative',
   'Accurate portrayal of a cop obsessed with catching a master thief in Heat.': 'Positive',
   'Accurate portrayal of union leader Jimmy Hoffa in The Irishman.': 'Positive',
   'Performance Accuracy Score': 80,
   'Factors Weightage': {'History': 0.3,
    'Storyline': 0.4,
    'Depth of Performance': 0.2,
    'Critical Acclaim': 0.1}},
  'Robert De Niro': {'Accurate portrayal of young Vito Corleone in The Godfather Part II.': 'Positive',
   'Accurate portrayal of a mentally unstable Vietnam veteran turned vigilante in Taxi Driver.': 'Positive',
   'Accurate portrayal of boxer Jake LaMotta in Raging Bull.': 'Positive',
   'Accurate portrayal of Jimmy Conway in Goodfellas.': 'Positive',
   'Less accurate portrayal of a vengeful ex-convict in Cape Fear.': 'Negative',
   'Performance Accuracy Score': 80,
   'Factors Weightage': {'History': 0.3,
    'Storyline': 0.4,
    'Depth of Performance': 0.2,
    'Critical Acclaim': 0.1}}},
 'actor_star_power': {'Al Pacino': {'Good Acting Score': 20,
   'Bad Acting Score': 80,
   'Performance Accuracy Score': 80,
   'Box Office Success': 90,
   'Factors Weightage': {'Good Acting': 0.2,
    'Bad Acting': -0.2,
    'Performance Accuracy': 0.4,
    'Box Office Success': 0.6},
   'Star Power': 68.8},
  'Robert De Niro': {'Good Acting Score': 50,
   'Bad Acting Score': 50,
   'Performance Accuracy Score': 80,
   'Box Office Success': 80,
   'Factors Weightage': {'Good Acting': 0.4,
    'Bad Acting': -0.4,
    'Performance Accuracy': 0.4,
    'Box Office Success': 0.2},
   'Star Power': 52},
  'Winner': 'Al Pacino',
  'Factors Where Al Pacino Surpassed Robert De Niro': ['Box Office Success'],
  'Calculation Steps': 'Star Power = (Good Acting Score * Good Acting Weightage) + (Bad Acting Score * Bad Acting Weightage) + (Performance Accuracy Score * Performance Accuracy Weightage) + (Box Office Success * Box Office Success Weightage)',
  'Box Office Success Explanation': "Al Pacino's movies have grossed more at the box office than Robert De Niro's movies on average, giving him a higher weightage in the Star Power calculation."}}

In [192]:
from langchain.output_parsers import ResponseSchema
from langchain.output_parsers import StructuredOutputParser
from langchain.prompts import ChatPromptTemplate
from langchain.chat_models import ChatOpenAI

In [206]:
chat = ChatOpenAI(model_name="gpt-3.5-turbo-16k", temperature=0.0, verbose="True")
chat

ChatOpenAI(verbose=True, callbacks=None, callback_manager=None, client=<class 'openai.api_resources.chat_completion.ChatCompletion'>, model_name='gpt-3.5-turbo-16k', temperature=0.0, model_kwargs={}, openai_api_key='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', openai_api_base='', openai_organization='', openai_proxy='', request_timeout=None, max_retries=6, streaming=False, n=1, max_tokens=None)

In [233]:
success_percentage_list_schema = ResponseSchema(name="success_percentage_list",
                             description="Go through all information provided, and based on these historical \
                             data, analyze, give proper weightages and find out the possible percentage (in format '%') of \
                             success for the two upcoming movies on these mentioned genres of these two actors\
                             each. Put all in a python dictionary format.")

release_time_list_schema = ResponseSchema(name="release_time_list",
                             description="Go through all information provided, analyze and tell us based on\
                             hitorical data provided, that in which month (could be a tentative timeline) \
                             of the current year these two upcoming movies of the two actors could be released \
                             to achieve maximum box office success. Put everything in a Python Dictionary format")

response_schemas_1 = [success_percentage_list_schema, 
                    release_time_list_schema]

In [234]:
user_prompt_1 = """- We have two upcoming movies of the two actors with no release date decided. What
                would be the possible success percentage of the movies of these two actors individually?\
                Both the movies are of Action Thriller genre.\
                - Going by the historical data provided to you, what could be the best time to release \
                the movies of these two actors to achieve the highest percentage of successs?"""

output_parser_1 = StructuredOutputParser.from_response_schemas(response_schemas_1)

format_instructions_1 = output_parser_1.get_format_instructions()

review_template_1 = """\
        You are a movie analyst who has to analyze, think, understand all the information given below \
        - movies_tags is having all information related to overview, keywords, cast, crew, genres of all \
        contemporary movies.
        - movies_profitability is having all the information related to budget, popularity, \
        production companies, production countries', release dates, revenue, runtime, average vote, \
        vote count of all the contemporary movies
        - data is having all information about the two actors starting from their list of awards, media \
        reviews, opinions and polls, social media followers till their performance criterions, 
        performance accuracy, their star power to influence success of a movie
        \
        in the instructed format, then come up with all the detailed points. Do not hallucinate, come \
        up with only real information.
        
        movies_tags: {movies_tags} 
        
        movies_profitability: {movies_profitability} \
        
        data: {data} 
        
        {format_instructions}
"""

prompt_1 = ChatPromptTemplate.from_template(template=review_template_1)

messages = prompt_1.format_messages(movies_tags=movies_tags, movies_profitability=movies_profitability,
                                    data=data, format_instructions=format_instructions_1)

#print(messages[0].content)
response = chat(messages)
output_dict_1 = output_parser_1.parse(response.content)
output_dict_1

{'success_percentage_list': {'Al Pacino': {'Action': '70%',
   'Drama': '80%',
   'Crime': '75%',
   'Thriller': '70%'},
  'Robert Di Niro': {'Action': '80%',
   'Drama': '85%',
   'Crime': '90%',
   'Thriller': '85%'}},
 'release_time_list': {'Al Pacino': 'September', 'Robert Di Niro': 'October'}}

## Using open source API's for information extraction

#### Getting a Movie/Tv-Series info
Use get_by_name(<name>, tv=False) method to get information of a movie/TV-Series.

The tv is an optional argument, if  tv=True it will get data from TV Series files only.

On the other hand, if tv=False (default), it will find your file in Movies + TV Series results

In [235]:
from PyMovieDb import IMDB
imdb = IMDB()
res = imdb.get_by_name('Mountain Men')
print(res)

{
  "type": "Movie",
  "name": "Mountain Men",
  "url": "https://www.imdb.comhttps://www.imdb.com/title/tt3529664/",
  "poster": "https://m.media-amazon.com/images/M/MV5BMjM5NDM1NTIzMF5BMl5BanBnXkFtZTgwMjY4NDg0NzE@._V1_.jpg",
  "description": "Mountain Men is a comedy/drama that follows two estranged brothers, Toph and Cooper, as they journey to a remote family cabin in the mountains to evict a squatter. Buried resentment and bruised egos soon derail the plan and when t...",
  "review": {
    "author": "elias-j-takacs",
    "dateCreated": "2016-02-07",
    "inLanguage": "English",
    "heading": "Nice Canadian film",
    "reviewBody": "Watched this on a plane back from Winnipeg. The great Canadian experience, visit Winnipeg, then watch a movie about 2 guys stuck in the Rockies. \n\nAlthough some parts of it is very typical Canadian, they do try to make it relatable to non-Canadians by adding a couple of interesting characteristics to each of the main characters in the movie. And I think they were on the right path but could have done more with it...become even more adventurous with the plot and explore the themes of fatherhood, wilderness, success (and failure), and in general the human condition. \n\nBut that might have compromised the realism and the message of real danger in situations such as this (which is very real). Canadian wilderness is very beautiful but can be dangerous as well if you&apos;re not properly prepared.",
    "reviewRating": {
      "worstRating": 1,
      "bestRating": 10,
      "ratingValue": 7
    }
  },
  "rating": {
    "ratingCount": 1732,
    "bestRating": 10,
    "worstRating": 1,
    "ratingValue": 5.9
  },
  "contentRating": "Not Rated",
  "genre": [
    "Comedy",
    "Drama"
  ],
  "datePublished": "2016-01-29",
  "keywords": "mountain,cabin,winter,survival,brother brother reunion",
  "duration": "PT1H25M",
  "actor": [
    {
      "name": "Chace Crawford",
      "url": "https://www.imdb.com/name/nm2003700/"
    },
    {
      "name": "Tyler Labine",
      "url": "https://www.imdb.com/name/nm0479527/"
    },
    {
      "name": "Christine Willes",
      "url": "https://www.imdb.com/name/nm0929794/"
    }
  ],
  "director": [
    {
      "name": "Cameron Labine",
      "url": "https://www.imdb.com/name/nm0479523/"
    }
  ],
  "creator": [
    {
      "name": "Cameron Labine",
      "url": "https://www.imdb.com/name/nm0479523/"
    },
    {
      "name": "Elan Mastai",
      "url": "https://www.imdb.com/name/nm0997459/"
    }
  ]
}

#### Getting a file Info by it's IMDB ID :-

Use get_by_id(<ID>) method to get a file information by it's IMDB ID.

In [90]:
from PyMovieDb import IMDB
imdb = IMDB()
res = imdb.get_by_id("tt10638522")
print(res)

{
  "type": "Movie",
  "name": "Talk to Me",
  "url": "https://www.imdb.comhttps://www.imdb.com/title/tt10638522/",
  "poster": "https://m.media-amazon.com/images/M/MV5BMmY5ZGE4NmUtZWI4OS00ZWJmLWFjMzgtOWUyZjI4NDg3Y2E5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
  "description": "When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.",
  "review": {
    "author": "zigmaen",
    "dateCreated": "2023-02-22",
    "inLanguage": "English",
    "heading": "Great debut",
    "reviewBody": "This movie really delivered. It has a certain Hereditary Vibe and at the same time came across with some fresh ideas and, for me, the most important aspect: a coherent atmosphere. Dang this movie triggered so many emotions and had great acting, great characters and so many good ideas. And I dont know how high the budget was, but it felt very big and i am sure it wasnt. There are so many creative ideas to raise the feeling of seeing a big budget movie but there was no time thinking about that while watching it. Can not wait to see how it does when it goes public. Thank you for this great experience!",
    "reviewRating": {
      "worstRating": 1,
      "bestRating": 10,
      "ratingValue": 10
    }
  },
  "rating": {
    "ratingCount": 655,
    "bestRating": 10,
    "worstRating": 1,
    "ratingValue": 7.4
  },
  "contentRating": "R",
  "genre": [
    "Horror",
    "Thriller"
  ],
  "datePublished": "2023-07-27",
  "keywords": "singing along to music on a car radio,singing in a car,title spoken by character,disembodied hand,supernatural vision",
  "duration": "PT1H34M",
  "actor": [
    {
      "name": "Sophie Wilde",
      "url": "https://www.imdb.com/name/nm12145223/"
    },
    {
      "name": "Joe Bird",
      "url": "https://www.imdb.com/name/nm12480921/"
    },
    {
      "name": "Alexandra Jensen",
      "url": "https://www.imdb.com/name/nm10325959/"
    }
  ],
  "director": [
    {
      "name": "Danny Philippou",
      "url": "https://www.imdb.com/name/nm4053334/"
    },
    {
      "name": "Michael Philippou",
      "url": "https://www.imdb.com/name/nm6100536/"
    }
  ],
  "creator": [
    {
      "name": "Bill Hinzman",
      "url": "https://www.imdb.com/name/nm5921025/"
    },
    {
      "name": "Daley Pearson",
      "url": "https://www.imdb.com/name/nm2587184/"
    },
    {
      "name": "Danny Philippou",
      "url": "https://www.imdb.com/name/nm4053334/"
    }
  ]
}

#### Getting a Person/Celebrity Profile Information:-

Use person_by_name(<name>) method to get profile info by name from IMDB.
Use person_by_id(<IMDB_ID>) method to get profile info by it's ID.

In [17]:
from PyMovieDb import IMDB
imdb = IMDB()
#res = imdb.person_by_name('Rajkummar Rao') #OR imdb.person_by_id("nm3822770")
res = imdb.person_by_id("nm0000093")
print(res)

{"status": 404, "message": "No Result Found!", "result_count": 0, "results": []}

#### Getting Popular Movies List by Genre :
The popular_movies() method will return 50 popular movies results starting from start_id

In [91]:
from PyMovieDb import IMDB
imdb = IMDB()
res = imdb.popular_movies(genre="Action", start_id=1, sort_by=None)
print(res)
# returns top 50 popular movies starting from start id
# genre, start_id & sort_by are **Optional args

{
  "result_count": 50,
  "results": [
    {
      "id": "tt0439572",
      "name": "The Flash",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt0439572/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWE2ZWE5MDQtMTJlZi00MTVjLTkxOTgtNmNiYjg2NDIxN2NhXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt9362722",
      "name": "Spider-Man: Across the Spider-Verse",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt9362722/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt5090568",
      "name": "Transformers: Rise of the Beasts",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt5090568/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZTNiNDA4NmMtNTExNi00YmViLWJkMDAtMDAxNmRjY2I2NDVjXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt1630029",
      "name": "Avatar: The Way of Water",
      "year": "2022",
      "url": "https://www.imdb.com/title/tt1630029/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_UY98_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt12263384",
      "name": "Extraction II",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt12263384/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZjg5MTM4N2QtN2RlMS00NzBlLTg3NDktM2ExZDNmMmExMGU3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt5433140",
      "name": "Fast X",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt5433140/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNzZmOTU1ZTEtYzVhNi00NzQxLWI5ZjAtNWNhNjEwY2E3YmZjXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt4633694",
      "name": "Spider-Man: Into the Spider-Verse",
      "year": "2018",
      "url": "https://www.imdb.com/title/tt4633694/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt10366206",
      "name": "John Wick: Chapter 4",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt10366206/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt1462764",
      "name": "Indiana Jones and the Dial of Destiny",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt1462764/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNDJhODYxYzItOGIwZC00ZTBiLTlmN2MtMjM2MzQyZDVkMGM4XkEyXkFqcGdeQXVyMTUzMDA3Mjc2._V1_UY98_CR5,0,67,98_AL_.jpg"
    },
    {
      "id": "tt6791350",
      "name": "Guardians of the Galaxy Vol. 3",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt6791350/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMDgxOTdjMzYtZGQxMS00ZTAzLWI4Y2UtMTQzN2VlYjYyZWRiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt4873118",
      "name": "Guy Ritchie's The Covenant",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt4873118/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNmQzOWZhOTMtZTcxNC00MTdkLWEwYmUtOWVmOTFhNTdkNjRkXkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt2906216",
      "name": "Dungeons & Dragons: Honor Among Thieves",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt2906216/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNmFkN2M2NzItOTY5YS00MmE2LTk3ZjctNTk2YzQ5ZmRiYzJjXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt3291150",
      "name": "Expend4bles",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt3291150/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjkwNWU2NjQtODVjNS00ZDg1LThkODEtM2RkYTYwYjBkZTA2XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt8936646",
      "name": "Extraction",
      "year": "2020",
      "url": "https://www.imdb.com/title/tt8936646/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMDJiNzUwYzEtNmQ2Yy00NWE4LWEwNzctM2M0MjE0OGUxZTA3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt12915716",
      "name": "Adipurush",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt12915716/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNGY3YmVmN2UtNWZiNy00YTRlLTlhOTItNzlkZmFmZDA1N2QzXkEyXkFqcGdeQXVyMTU4Mzg1OTU2._V1_UY98_CR5,0,67,98_AL_.jpg"
    },
    {
      "id": "tt5761544",
      "name": "Kandahar",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt5761544/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjNiNDg2OWYtOGEzNy00M2E5LTgxZjItNzVmN2VmNTg3MzBhXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt14846026",
      "name": "Sisu",
      "year": "2022",
      "url": "https://www.imdb.com/title/tt14846026/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMWYwMzNkOWEtNjA3YS00YjE5LTlkMjYtMmRjMjExNjA1NDM0XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt10954600",
      "name": "Ant-Man and the Wasp: Quantumania",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt10954600/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BODZhNzlmOGItMWUyYS00Y2Q5LWFlNzMtM2I2NDFkM2ZkYmE1XkEyXkFqcGdeQXVyMTU5OTA4NTIz._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt0499549",
      "name": "Avatar",
      "year": "2009",
      "url": "https://www.imdb.com/title/tt0499549/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt27501039",
      "name": "Bloody Daddy",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt27501039/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNjA3NmJiZGYtY2Y4Mi00OTljLWFiZDUtMDRmZWM2NmI5MWJkXkEyXkFqcGdeQXVyMTY0NjI3Mjcx._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt10151854",
      "name": "Shazam! Fury of the Gods",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt10151854/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNzJlM2NmZTItOGQyYS00MmE2LTkwZGUtNDFkNmJmZjRjZjcxXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt9603212",
      "name": "Mission: Impossible - Dead Reckoning Part One",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt9603212/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMDkyMmZlN2EtMzhlNC00ODc5LTk0ODgtOWRlNzRkYzRkNTdmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt0082971",
      "name": "Raiders of the Lost Ark",
      "year": "1981",
      "url": "https://www.imdb.com/title/tt0082971/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNTU2ODkyY2MtMjU1NC00NjE1LWEzYjgtMWQ3MzRhMTE0NDc0XkEyXkFqcGdeQXVyMjM4MzQ4OTQ@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt8080204",
      "name": "Hypnotic",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt8080204/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNmNmNWNiMjUtZmYyMC00OWVhLThmMTItNjkxYzU4Yzk2NTdlXkEyXkFqcGdeQXVyMDc5ODIzMw@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt1160419",
      "name": "Dune: Part One",
      "year": "2021",
      "url": "https://www.imdb.com/title/tt1160419/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt16360004",
      "name": "Spider-Man: Beyond the Spider-Verse",
      "year": "2024",
      "url": "https://www.imdb.com/title/tt16360004/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYWJlNThmNWMtZWE5Zi00YWJiLWJiOTQtZWY1Y2I3ZmNhMDYwXkEyXkFqcGdeQXVyMTk2OTAzNTI@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt0418279",
      "name": "Transformers",
      "year": "2007",
      "url": "https://www.imdb.com/title/tt0418279/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNWI1NjkxM2MtOTU4My00YzQ5LTliNGMtNmFlM2U5NWM3MDY1XkEyXkFqcGdeQXVyNTUyMzE4Mzg@._V1_UY98_CR1,0,67,98_AL_.jpg"
    },
    {
      "id": "tt9218128",
      "name": "Gladiator 2",
      "year": "2024",
      "url": "https://www.imdb.com/title/tt9218128/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/S/sash/NapCxx-VwSOJtCZ.png"
    },
    {
      "id": "tt0107290",
      "name": "Jurassic Park",
      "year": "1993",
      "url": "https://www.imdb.com/title/tt0107290/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt1745960",
      "name": "Top Gun: Maverick",
      "year": "2022",
      "url": "https://www.imdb.com/title/tt1745960/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt19500164",
      "name": "Nimona",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt19500164/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYWQ2YzJhOGItNTMyOC00YzFmLWExZjEtOGFmMDVkMDdmOGFiXkEyXkFqcGdeQXVyMTUxNTU1NzEz._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt11040844",
      "name": "The Machine",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt11040844/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNjAwMzk1YzEtOGJjOS00Mjg3LTllNGItMGYxNWI0ZTI1MTk3XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt10872600",
      "name": "Spider-Man: No Way Home",
      "year": "2021",
      "url": "https://www.imdb.com/title/tt10872600/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt6710474",
      "name": "Everything Everywhere All at Once",
      "year": "2022",
      "url": "https://www.imdb.com/title/tt6710474/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_UY98_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt12261776",
      "name": "65",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt12261776/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYzFhM2M1MDUtNDhmNC00YzEzLThiMzctYWYxZTc0MGJhNWYyXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UY98_CR5,0,67,98_AL_.jpg"
    },
    {
      "id": "tt1375666",
      "name": "Inception",
      "year": "2010",
      "url": "https://www.imdb.com/title/tt1375666/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt1877830",
      "name": "The Batman",
      "year": "2022",
      "url": "https://www.imdb.com/title/tt1877830/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt15239678",
      "name": "Dune: Part Two",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt15239678/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BODI0YjNhNjUtYjM0My00MTUwLWFlYTMtMWI2NGUzYjNjNGQzXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt0468569",
      "name": "The Dark Knight",
      "year": "2008",
      "url": "https://www.imdb.com/title/tt0468569/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt6968614",
      "name": "The Mother",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt6968614/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BODlmZThjZGItOGRmMC00ODVjLWIzYWMtODBhYzQyZjE4NWE5XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt3371366",
      "name": "Transformers: The Last Knight",
      "year": "2017",
      "url": "https://www.imdb.com/title/tt3371366/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BN2YwOWM4ODgtZTMzMi00ZmFmLTk5NTEtNmY4ZDcwNzQxNDhjXkEyXkFqcGdeQXVyNTI0NzAyNjY@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt15326988",
      "name": "Ghosted",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt15326988/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNGMzYWZlYmYtNTcyMC00ZGVjLThjN2ItMjY4MjkwN2NlMjYwXkEyXkFqcGdeQXVyOTU0NjY1MDM@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt0087469",
      "name": "Indiana Jones and the Temple of Doom",
      "year": "1984",
      "url": "https://www.imdb.com/title/tt0087469/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYzgzMTIzNzctNmNiZC00ZDYyLWJjNzktMmQ2MDM2ZDkwZGVhXkEyXkFqcGdeQXVyMjM4MzQ4OTQ@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt10275534",
      "name": "Misanthrope",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt10275534/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNGMyZjM5YWUtMjVmMC00NmQ2LTgyMWEtNjYzZDFkYTIyMjFhXkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt18073328",
      "name": "Blood & Gold",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt18073328/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BOTVlMDI5NDMtOGE1Zi00ZmEwLTg3NDQtMzgxOWNkNWE5YmE2XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_UY98_CR7,0,67,98_AL_.jpg"
    },
    {
      "id": "tt0113277",
      "name": "Heat",
      "year": "1995",
      "url": "https://www.imdb.com/title/tt0113277/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYjZjNTJlZGUtZTE1Ny00ZDc4LTgwYjUtMzk0NDgwYzZjYTk1XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY98_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt12593682",
      "name": "Bullet Train",
      "year": "2022",
      "url": "https://www.imdb.com/title/tt12593682/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMDU2ZmM2OTYtNzIxYy00NjM5LTliNGQtN2JmOWQzYTBmZWUzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt2911666",
      "name": "John Wick",
      "year": "2014",
      "url": "https://www.imdb.com/title/tt2911666/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt5433138",
      "name": "F9",
      "year": "2021",
      "url": "https://www.imdb.com/title/tt5433138/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjI0NmFkYzEtNzU2YS00NTg5LWIwYmMtNmQ1MTU0OGJjOTMxXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt4701182",
      "name": "Bumblebee",
      "year": "2018",
      "url": "https://www.imdb.com/title/tt4701182/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjUwNjU5NDMyNF5BMl5BanBnXkFtZTgwNzgxNjM2NzM@._V1_UX67_CR0,0,67,98_AL_.jpg"
    }
  ]
}

#### Getting Popular TV Series List by Genre :
The popular_tv() method will return 50 popular TV-Series starting from start_id

In [22]:
from PyMovieDb import IMDB
imdb = IMDB()
res = imdb.popular_tv(genre="Horror", start_id=1, sort_by=None)
print(res)
# returns top 50 popular TV Series starting from start id
# genre, start_id & sort_by are **Optional args

{
  "result_count": 50,
  "results": [
    {
      "id": "tt9813792",
      "name": "From",
      "year": "2022",
      "url": "https://www.imdb.com/title/tt9813792/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNDQxOGI4ZjItM2NhZC00Y2FhLWEwZTAtZTc2MmJmNzY1MjViXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt1520211",
      "name": "The Walking Dead",
      "year": "2010-2022",
      "url": "https://www.imdb.com/title/tt1520211/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZmU5NTcwNjktODIwMi00ZmZkLTk4ZWUtYzVjZWQ5ZTZjN2RlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt11041332",
      "name": "Yellowjackets",
      "year": "2021",
      "url": "https://www.imdb.com/title/tt11041332/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTkzYTBkYmItN2Q0Zi00ODhiLWI3MzEtNDdiNDRkNWYzOTMyXkEyXkFqcGdeQXVyMTUyMTgzNjY4._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt18546730",
      "name": "The Walking Dead: Dead City",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt18546730/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMzczNjBlYmYtMjEwYi00MzJhLWFkOTUtNjViNzEzMGM5YWJmXkEyXkFqcGdeQXVyMTMzOTQyOTk1._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt4574334",
      "name": "Stranger Things",
      "year": "2016-2024",
      "url": "https://www.imdb.com/title/tt4574334/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGMzZWI1ZjhlOWJmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY98_CR5,0,67,98_AL_.jpg"
    },
    {
      "id": "tt3581920",
      "name": "The Last of Us",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt3581920/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZGUzYTI3M2EtZmM0Yy00NGUyLWI4ODEtN2Q3ZGJlYzhhZjU3XkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt0460681",
      "name": "Supernatural",
      "year": "2005-2020",
      "url": "https://www.imdb.com/title/tt0460681/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNzRmZWJhNjUtY2ZkYy00N2MyLWJmNTktOTAwY2VkODVmOGY3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt3743822",
      "name": "Fear the Walking Dead",
      "year": "2015-2023",
      "url": "https://www.imdb.com/title/tt3743822/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWQ2NGZhMTktMzJjZi00ZTNjLTljZjMtMzU0ODU1OWNhOTY1XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt9174630",
      "name": "The Horror of Dolores Roach",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt9174630/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjAxMDZlNWItODBkOS00NGQ5LWIxNDItZWIxY2VmMzhiYTBhXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt2560140",
      "name": "Shingeki no Kyojin",
      "year": "2013-2023",
      "url": "https://www.imdb.com/title/tt2560140/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNDFjYTIxMjctYTQ2ZC00OGQ4LWE3OGYtNDdiMzNiNDZlMDAwXkEyXkFqcGdeQXVyNzI3NjY3NjQ@._V1_UY98_CR3,0,67,98_AL_.jpg"
    },
    {
      "id": "tt7908628",
      "name": "What We Do in the Shadows",
      "year": "2019",
      "url": "https://www.imdb.com/title/tt7908628/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNWYwNGMwNTItMzZiNS00YTNhLTg5ZDItOTE5YzdhYWRjOWQ2XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UY98_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt1844624",
      "name": "American Horror Story",
      "year": "2011",
      "url": "https://www.imdb.com/title/tt1844624/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BOWFlOWE1OGEtOTVlMi00M2JmLWJlMGEtOWVjOGFhOTNlYTZiXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt1405406",
      "name": "The Vampire Diaries",
      "year": "2009-2017",
      "url": "https://www.imdb.com/title/tt1405406/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMDk3YzgxNDQtNTEzOS00NDMyLWFlYmYtYTZlMDk1NDkxNmMyXkEyXkFqcGdeQXVyNzA5NjUyNjM@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt9561862",
      "name": "Love, Death & Robots",
      "year": "2019",
      "url": "https://www.imdb.com/title/tt9561862/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYTNiYTNkNTAtYzE3ZS00ZDQ1LWEwZTYtZjI1NzYzMWJjY2U4XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt1751634",
      "name": "The Sandman",
      "year": "2022",
      "url": "https://www.imdb.com/title/tt1751634/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYTM0NjZjYjItM2JiYS00NmU5LWJmMTMtZjQ0OWU3Mzk1ZWZjXkEyXkFqcGdeQXVyMTAxNDE3MTE5._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt10313176",
      "name": "Nancy Drew",
      "year": "2019-2023",
      "url": "https://www.imdb.com/title/tt10313176/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BN2Y1ZTdhYjAtZTU5ZS00MGNlLWI2MjAtNzMyNjVlOWEzN2ExXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt2243973",
      "name": "Hannibal",
      "year": "2013-2015",
      "url": "https://www.imdb.com/title/tt2243973/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNWU5YmJhNWEtZGVlOS00NmRhLThmNzUtYjAyMDA2MDg5ZTM4XkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_UY98_CR1,0,67,98_AL_.jpg"
    },
    {
      "id": "tt0052520",
      "name": "The Twilight Zone",
      "year": "1959-1964",
      "url": "https://www.imdb.com/title/tt0052520/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNTAzMDI5MzgtMGNkMC00MzllLWJhNjctNjA1NmViNGUxMzYxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt2632424",
      "name": "The Originals",
      "year": "2013-2018",
      "url": "https://www.imdb.com/title/tt2632424/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNDllZjc2NjEtOGMwZS00ZmNkLTg2NDgtZjJkYjg0YjMxM2FmXkEyXkFqcGdeQXVyNzA5NjUyNjM@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt6763664",
      "name": "The Haunting of Hill House",
      "year": "2018",
      "url": "https://www.imdb.com/title/tt6763664/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTU4NzA4MDEwNF5BMl5BanBnXkFtZTgwMTQxODYzNjM@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt9055008",
      "name": "Evil",
      "year": "2019",
      "url": "https://www.imdb.com/title/tt9055008/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BY2RiM2FkNjEtNzZhMS00MmY4LWIyMjUtNWExMzIyNDQ2YjY4XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt14852808",
      "name": "The Watcher",
      "year": "2022",
      "url": "https://www.imdb.com/title/tt14852808/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTY3OGQxNTItYWEwZS00ZTg0LWE1MjYtMTcxNTUzYzk0ZjdmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt2674806",
      "name": "Inside No. 9",
      "year": "2014",
      "url": "https://www.imdb.com/title/tt2674806/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYzQyNTcwYjctZDYxZi00OTg1LThkNzItNzI1ZGMzMzM4OTM2XkEyXkFqcGdeQXVyMTA0MTM5NjI2._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt8068860",
      "name": "Servant",
      "year": "2019-2023",
      "url": "https://www.imdb.com/title/tt8068860/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNDNiOWE4Y2YtMDZiOS00OGFlLWIyN2QtYjA0MmFlOWY0NDRkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt9319668",
      "name": "1899",
      "year": "2022",
      "url": "https://www.imdb.com/title/tt9319668/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTU1N2I5OTgtNDE2MS00ZTdmLWJlODktNDMwMGVmNzY5NmUxXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UY98_CR5,0,67,98_AL_.jpg"
    },
    {
      "id": "tt8550800",
      "name": "The Outsider",
      "year": "2020",
      "url": "https://www.imdb.com/title/tt8550800/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNzgxOTc4ODctNDNhZC00M2UzLTgyYzgtM2Q2OTk3NmQ5NTljXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt1865718",
      "name": "Gravity Falls",
      "year": "2012-2016",
      "url": "https://www.imdb.com/title/tt1865718/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTEzNDc3MDQ2NzNeQTJeQWpwZ15BbWU4MDYzMzUwMDIx._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt12923632",
      "name": "Dead Ringers",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt12923632/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNTNlNDUyMGYtMzA2ZS00YjkyLWJmNjgtNjdiNzUzYmU3MTVkXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt8415836",
      "name": "Guillermo del Toro's Cabinet of Curiosities",
      "year": "2022",
      "url": "https://www.imdb.com/title/tt8415836/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYTFlZGMyMzEtZDAyZi00MTY4LWI4OWQtYmVjN2JlZDJmOGYyXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UY98_CR5,0,67,98_AL_.jpg"
    },
    {
      "id": "tt2654620",
      "name": "The Strain",
      "year": "2014-2017",
      "url": "https://www.imdb.com/title/tt2654620/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNjQxNzVlNjQtMTg3YS00MzBmLThkNzAtMzMyNDUyMTVlNzg0XkEyXkFqcGdeQXVyOTQxNzM2MjY@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt10574558",
      "name": "Midnight Mass",
      "year": "2021",
      "url": "https://www.imdb.com/title/tt10574558/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNWVmZWQ5ZmItZjc2OC00MTFhLWI4OTEtNWY3MDg0OWY3YTJjXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt4667888",
      "name": "Slasher",
      "year": "2016",
      "url": "https://www.imdb.com/title/tt4667888/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYzc3ZWFhNzItMGRkMi00YWQxLWIxN2YtZjQ0MDVlNTExMzJjXkEyXkFqcGdeQXVyMTQ5MDIxMzkw._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt4093826",
      "name": "Twin Peaks",
      "year": "2017",
      "url": "https://www.imdb.com/title/tt4093826/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZWZiNWI0MzgtMDMyYS00NDY2LWI0Y2YtNTQ2ZWJhNzU2NTEyXkEyXkFqcGdeQXVyOTA3MTMyOTk@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt8103070",
      "name": "Legacies",
      "year": "2018-2022",
      "url": "https://www.imdb.com/title/tt8103070/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZmMwNDczMDUtNDU0Mi00MjIyLWI1NTktNzM4Yzc1MTNmZDIxXkEyXkFqcGdeQXVyOTQ0NTEzMzk@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt15428778",
      "name": "Anne Rice's Mayfair Witches",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt15428778/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNzIyZjYzYjgtYzQwNC00MGY4LWJhMTAtMDIzMTZiMGE0YjkxXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt1831804",
      "name": "The Stand",
      "year": "2020-2021",
      "url": "https://www.imdb.com/title/tt1831804/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNzNlZGJmNGItNzE0Ny00Yzc5LTk0NDQtODRkNWYwMTE2MDVlXkEyXkFqcGdeQXVyMTI3MjgxNjg0._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt3007572",
      "name": "Locke & Key",
      "year": "2020-2022",
      "url": "https://www.imdb.com/title/tt3007572/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BNzVkOTIxZWUtMTNjOC00NWMwLWEyNDQtNTY2NzYxNjhhYTA1XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UY98_CR5,0,67,98_AL_.jpg"
    },
    {
      "id": "tt2359704",
      "name": "JoJo no Kimy\u00f4 na B\u00f4ken",
      "year": "2012",
      "url": "https://www.imdb.com/title/tt2359704/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZDc3NGQ3ZWQtYjNkOC00MjhiLTg2N2YtNmZlOGNiZTFkOWNhXkEyXkFqcGdeQXVyNjc2NjA5MTU@._V1_UY98_CR1,0,67,98_AL_.jpg"
    },
    {
      "id": "tt2188671",
      "name": "Bates Motel",
      "year": "2013-2017",
      "url": "https://www.imdb.com/title/tt2188671/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMzk4OTU5NTE2M15BMl5BanBnXkFtZTcwNTIxMDIyOQ@@._V1_UY98_CR3,0,67,98_AL_.jpg"
    },
    {
      "id": "tt10589968",
      "name": "The Secret of Skinwalker Ranch",
      "year": "2020",
      "url": "https://www.imdb.com/title/tt10589968/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYjEzNWZkNzktYTI2Yi00MjY4LWFkNGMtMjcwMDk5OTBmMmM0XkEyXkFqcGdeQXVyMTI0MDY5NzI@._V1_UY98_CR3,0,67,98_AL_.jpg"
    },
    {
      "id": "tt9859436",
      "name": "The Walking Dead: Summit",
      "year": "2024",
      "url": "https://www.imdb.com/title/tt9859436/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZGQ0ZTYwN2ItNWY1Yi00YzgwLWEyY2MtMjRiYzk5NmNmMTk5XkEyXkFqcGdeQXVyNjg3MDMxNzU@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt8388390",
      "name": "Chucky",
      "year": "2021",
      "url": "https://www.imdb.com/title/tt8388390/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BZjkzNGJiZjctMmEwMi00ZGFhLWE4MGMtZmFiZGZkMTg5NmNlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt14921986",
      "name": "Interview with the Vampire",
      "year": "2022",
      "url": "https://www.imdb.com/title/tt14921986/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMmJiMTA0ZDctMTQ1OS00Y2FhLWI4MjUtZWRkMmU5ZjA2MTM3XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt14169960",
      "name": "Ji-geum u-ri hak-gyo-neun",
      "year": "2022",
      "url": "https://www.imdb.com/title/tt14169960/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BOTY1ZGM2YzQtMTBjZC00NjE2LWJlNzUtYjA0YjYxNzBjMmRjXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt13802576",
      "name": "Lockwood & Co.",
      "year": "2023",
      "url": "https://www.imdb.com/title/tt13802576/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BY2RiOGNmMmYtNmFlOC00MDg2LTk2YTItZWRmMmZjZjc1OGMxXkEyXkFqcGdeQXVyMTYxMDYwMzI2._V1_UY98_CR5,0,67,98_AL_.jpg"
    },
    {
      "id": "tt8050756",
      "name": "The Owl House",
      "year": "2020-2023",
      "url": "https://www.imdb.com/title/tt8050756/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BOGQ0MDQyYWMtNjdlYy00ZDAyLWE5YTItMzcyMjllZTA4MTcyXkEyXkFqcGdeQXVyMjEzNTg5Mzk@._V1_UY98_CR1,0,67,98_AL_.jpg"
    },
    {
      "id": "tt2628232",
      "name": "Penny Dreadful",
      "year": "2014-2016",
      "url": "https://www.imdb.com/title/tt2628232/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMTNiMDBmZWQtZDI4Ni00ZGViLWJlOWMtNTdkODNlMTFkZjc2XkEyXkFqcGdeQXVyOTA3MTMyOTk@._V1_UY98_CR2,0,67,98_AL_.jpg"
    },
    {
      "id": "tt6517102",
      "name": "Castlevania",
      "year": "2017-2021",
      "url": "https://www.imdb.com/title/tt6517102/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMjAzMjU2MjYzMl5BMl5BanBnXkFtZTgwNTQ4Nzk1NjM@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt0099864",
      "name": "It",
      "year": "1990",
      "url": "https://www.imdb.com/title/tt0099864/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BYjg1YTRkNzQtODgyYi00MTQ5LThiMDYtNDJjMWRjNTdjZDZlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX67_CR0,0,67,98_AL_.jpg"
    },
    {
      "id": "tt2583620",
      "name": "The Twilight Zone",
      "year": "2019-2020",
      "url": "https://www.imdb.com/title/tt2583620/?ref_=adv_li_tt",
      "poster": "https://m.media-amazon.com/images/M/MV5BMzBkMTU3MzktMDhhYS00NzQ4LTkwMzItYTM5MDBkZWYwNzM4XkEyXkFqcGdeQXVyMTI3MjgxNjg0._V1_UX67_CR0,0,67,98_AL_.jpg"
    }
  ]
}

## Using IMDP API

In [46]:
!pip install IMDbPY

Collecting IMDbPY
  Downloading IMDbPY-2022.7.9-py3-none-any.whl (1.2 kB)
Collecting cinemagoer
  Downloading cinemagoer-2023.5.1-py3-none-any.whl (297 kB)
     ---------------------------------------- 0.0/297.2 kB ? eta -:--:--
     ---- ---------------------------------- 30.7/297.2 kB 1.3 MB/s eta 0:00:01
     ---- ---------------------------------- 30.7/297.2 kB 1.3 MB/s eta 0:00:01
     ---- ---------------------------------- 30.7/297.2 kB 1.3 MB/s eta 0:00:01
     ---- ---------------------------------- 30.7/297.2 kB 1.3 MB/s eta 0:00:01
     ----- ------------------------------- 41.0/297.2 kB 130.7 kB/s eta 0:00:02
     ----- ------------------------------- 41.0/297.2 kB 130.7 kB/s eta 0:00:02
     -------- ---------------------------- 71.7/297.2 kB 196.3 kB/s eta 0:00:02
     ------------- ---------------------- 112.6/297.2 kB 284.4 kB/s eta 0:00:01
     -------------- --------------------- 122.9/297.2 kB 277.4 kB/s eta 0:00:01
     ----------------- ------------------ 143.4/297.2 kB 315.4 kB/s eta 0:00:01
     ------------------ ----------------- 153.6/297.2 kB 295.6 kB/s eta 0:00:01
     --------------------------- -------- 225.3/297.2 kB 382.0 kB/s eta 0:00:01
     --------------------------------- -- 276.5/297.2 kB 448.2 kB/s eta 0:00:01
     -----------------------------------  297.0/297.2 kB 470.0 kB/s eta 0:00:01
     ------------------------------------ 297.2/297.2 kB 427.0 kB/s eta 0:00:00
Requirement already satisfied: lxml in c:\users\340103\anaconda3\envs\aiml-python-3_8\lib\site-packages (from cinemagoer->IMDbPY) (4.9.2)
Requirement already satisfied: SQLAlchemy in c:\users\340103\anaconda3\envs\aiml-python-3_8\lib\site-packages (from cinemagoer->IMDbPY) (2.0.15)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\340103\anaconda3\envs\aiml-python-3_8\lib\site-packages (from SQLAlchemy->cinemagoer->IMDbPY) (2.0.2)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\340103\anaconda3\envs\aiml-python-3_8\lib\site-packages (from SQLAlchemy->cinemagoer->IMDbPY) (4.5.0)
Installing collected packages: cinemagoer, IMDbPY
Successfully installed IMDbPY-2022.7.9 cinemagoer-2023.5.1

In [237]:
# importing the module
import imdb

# creating instance of IMDb
ia = imdb.IMDb()

# id
code = "6077448"

# getting information
series = ia.get_movie(code)

# adding new info set
ia.update(series, 'episodes')

# getting episodes of the series
episodes = series.data['episodes']

# printing the object i.e name
print(series)

print("==================")

# printing episodes
print(episodes)

Sacred Games
==================
{1: {1: <Movie id:8058636[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Ashwathama (2018)_>, 2: <Movie id:8661620[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Halahala (2018)_>, 3: <Movie id:8661622[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Aatapi Vatapi (2018)_>, 4: <Movie id:8661624[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Brahmahatya (2018)_>, 5: <Movie id:8648742[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Sarama (2018)_>, 6: <Movie id:8648708[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Pretakalpa (2018)_>, 7: <Movie id:8648710[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Rudra (2018)_>, 8: <Movie id:8648716[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Yayati (2018)_>}, 2: {1: <Movie id:9043234[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Matsya (2019)_>, 2: <Movie id:9043238[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Siduri (2019)_>, 3: <Movie id:9043240[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Apasmara (2019)_>, 4: <Movie id:9043242[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Bardo (2019)_>, 5: <Movie id:9043246[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Vikarna (2019)_>, 6: <Movie id:9043248[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Azrael (2019)_>, 7: <Movie id:9043250[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Torino (2019)_>, 8: <Movie id:9043252[http] title:_"Sacred Games (TV Series 2018–2019) - IMDb" Radcliffe (2019)_>}}